// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TempoScripting/Empty.proto

#include "TempoScripting/Empty.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf_tempo;
namespace _pbi = ::google::protobuf_tempo::internal;
namespace _fl = ::google::protobuf_tempo::internal::field_layout;
namespace TempoScripting {
      template <typename>
PROTOBUF_CONSTEXPR Empty::Empty(::_pbi::ConstantInitialized) {}
struct EmptyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyDefaultTypeInternal() {}
  union {
    Empty _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT TEMPOSCRIPTING_API
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyDefaultTypeInternal _Empty_default_instance_;
}  // namespace TempoScripting
static ::_pb::Metadata file_level_metadata_TempoScripting_2fEmpty_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_TempoScripting_2fEmpty_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_TempoScripting_2fEmpty_2eproto = nullptr;
const ::uint32_t TableStruct_TempoScripting_2fEmpty_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::TempoScripting::Empty, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::TempoScripting::Empty)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::TempoScripting::_Empty_default_instance_._instance,
};
const char descriptor_table_protodef_TempoScripting_2fEmpty_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\032TempoScripting/Empty.proto\022\016TempoScrip"
    "ting\"\007\n\005Emptyb\006proto3"
};
static ::absl_tempo::once_flag descriptor_table_TempoScripting_2fEmpty_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_TempoScripting_2fEmpty_2eproto = {
    false,
    false,
    61,
    descriptor_table_protodef_TempoScripting_2fEmpty_2eproto,
    "TempoScripting/Empty.proto",
    &descriptor_table_TempoScripting_2fEmpty_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_TempoScripting_2fEmpty_2eproto::offsets,
    file_level_metadata_TempoScripting_2fEmpty_2eproto,
    file_level_enum_descriptors_TempoScripting_2fEmpty_2eproto,
    file_level_service_descriptors_TempoScripting_2fEmpty_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_TempoScripting_2fEmpty_2eproto_getter() {
  return &descriptor_table_TempoScripting_2fEmpty_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_TempoScripting_2fEmpty_2eproto(&descriptor_table_TempoScripting_2fEmpty_2eproto);
namespace TempoScripting {
// ===================================================================

class Empty::_Internal {
 public:
};

Empty::Empty(::google::protobuf_tempo::Arena* arena)
    : ::google::protobuf_tempo::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:TempoScripting.Empty)
}
Empty::Empty(
    ::google::protobuf_tempo::Arena* arena,
    const Empty& from)
    : ::google::protobuf_tempo::internal::ZeroFieldsBase(arena) {
  Empty* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf_tempo::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:TempoScripting.Empty)
}









::google::protobuf_tempo::Metadata Empty::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_TempoScripting_2fEmpty_2eproto_getter, &descriptor_table_TempoScripting_2fEmpty_2eproto_once,
      file_level_metadata_TempoScripting_2fEmpty_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace TempoScripting
namespace google {
namespace protobuf_tempo {
}  // namespace protobuf_tempo
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
