# Warning: Autogenerated code do not edit

from tempo._tempo_context import tempo_context
from tempo import run_async
from curio.meta import awaitable
import asyncio


import TempoCore.Empty_pb2, TempoMovement.MovementControlService_pb2, TempoMovement.MovementControlService_pb2_grpc
async def _get_commandable_pawns(
) -> TempoMovement.MovementControlService_pb2.CommandablePawnsResponse:
    stub = await tempo_context().get_stub(TempoMovement.MovementControlService_pb2_grpc.MovementControlServiceStub)
    request = TempoCore.Empty_pb2.Empty(
    )
    return await stub.GetCommandablePawns(request)


def get_commandable_pawns(
) -> TempoMovement.MovementControlService_pb2.CommandablePawnsResponse:
    return run_async(_get_commandable_pawns(
    ))


@awaitable(get_commandable_pawns)
async def get_commandable_pawns(
) -> TempoMovement.MovementControlService_pb2.CommandablePawnsResponse:
    return await _get_commandable_pawns(
    )

import TempoCore.Empty_pb2, TempoMovement.MovementControlService_pb2, TempoMovement.MovementControlService_pb2_grpc
async def _command_vehicle(
    vehicle: str = '',
    acceleration: float = 0.0,
    steering: float = 0.0
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoMovement.MovementControlService_pb2_grpc.MovementControlServiceStub)
    request = TempoMovement.MovementControlService_pb2.NormalizedDrivingCommand(
        vehicle=vehicle,
        acceleration=acceleration,
        steering=steering
    )
    return await stub.CommandVehicle(request)


def command_vehicle(
    vehicle: str = '',
    acceleration: float = 0.0,
    steering: float = 0.0
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_command_vehicle(
        vehicle=vehicle,
        acceleration=acceleration,
        steering=steering
    ))


@awaitable(command_vehicle)
async def command_vehicle(
    vehicle: str = '',
    acceleration: float = 0.0,
    steering: float = 0.0
) -> TempoCore.Empty_pb2.Empty:
    return await _command_vehicle(
        vehicle=vehicle,
        acceleration=acceleration,
        steering=steering
    )

import TempoCore.Empty_pb2, TempoCore.Geometry_pb2, TempoMovement.MovementControlService_pb2, TempoMovement.MovementControlService_pb2_grpc
async def _command_velocity(
    pawn: str = '',
    twist: TempoCore.Geometry_pb2.Twist = None
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoMovement.MovementControlService_pb2_grpc.MovementControlServiceStub)
    request = TempoMovement.MovementControlService_pb2.VelocityCommand(
        pawn=pawn,
        twist=twist
    )
    return await stub.CommandVelocity(request)


def command_velocity(
    pawn: str = '',
    twist: TempoCore.Geometry_pb2.Twist = None
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_command_velocity(
        pawn=pawn,
        twist=twist
    ))


@awaitable(command_velocity)
async def command_velocity(
    pawn: str = '',
    twist: TempoCore.Geometry_pb2.Twist = None
) -> TempoCore.Empty_pb2.Empty:
    return await _command_velocity(
        pawn=pawn,
        twist=twist
    )

import TempoCore.Empty_pb2, TempoCore.Geometry_pb2, TempoMovement.MovementControlService_pb2, TempoMovement.MovementControlService_pb2_grpc
async def _command_acceleration(
    pawn: str = '',
    accel: TempoCore.Geometry_pb2.Accel = None
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoMovement.MovementControlService_pb2_grpc.MovementControlServiceStub)
    request = TempoMovement.MovementControlService_pb2.AccelerationCommand(
        pawn=pawn,
        accel=accel
    )
    return await stub.CommandAcceleration(request)


def command_acceleration(
    pawn: str = '',
    accel: TempoCore.Geometry_pb2.Accel = None
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_command_acceleration(
        pawn=pawn,
        accel=accel
    ))


@awaitable(command_acceleration)
async def command_acceleration(
    pawn: str = '',
    accel: TempoCore.Geometry_pb2.Accel = None
) -> TempoCore.Empty_pb2.Empty:
    return await _command_acceleration(
        pawn=pawn,
        accel=accel
    )

import TempoCore.Empty_pb2, TempoMovement.MovementControlService_pb2, TempoMovement.MovementControlService_pb2_grpc
async def _get_navigable_pawns(
) -> TempoMovement.MovementControlService_pb2.NavigablePawnsResponse:
    stub = await tempo_context().get_stub(TempoMovement.MovementControlService_pb2_grpc.MovementControlServiceStub)
    request = TempoCore.Empty_pb2.Empty(
    )
    return await stub.GetNavigablePawns(request)


def get_navigable_pawns(
) -> TempoMovement.MovementControlService_pb2.NavigablePawnsResponse:
    return run_async(_get_navigable_pawns(
    ))


@awaitable(get_navigable_pawns)
async def get_navigable_pawns(
) -> TempoMovement.MovementControlService_pb2.NavigablePawnsResponse:
    return await _get_navigable_pawns(
    )

import TempoCore.Geometry_pb2, TempoMovement.MovementControlService_pb2, TempoMovement.MovementControlService_pb2_grpc
async def _pawn_move_to_location(
    pawn: str = '',
    location: TempoCore.Geometry_pb2.Vector = None,
    relative: bool = False
) -> TempoMovement.MovementControlService_pb2.PawnMoveToLocationResponse:
    stub = await tempo_context().get_stub(TempoMovement.MovementControlService_pb2_grpc.MovementControlServiceStub)
    request = TempoMovement.MovementControlService_pb2.PawnMoveToLocationRequest(
        pawn=pawn,
        location=location,
        relative=relative
    )
    return await stub.PawnMoveToLocation(request)


def pawn_move_to_location(
    pawn: str = '',
    location: TempoCore.Geometry_pb2.Vector = None,
    relative: bool = False
) -> TempoMovement.MovementControlService_pb2.PawnMoveToLocationResponse:
    return run_async(_pawn_move_to_location(
        pawn=pawn,
        location=location,
        relative=relative
    ))


@awaitable(pawn_move_to_location)
async def pawn_move_to_location(
    pawn: str = '',
    location: TempoCore.Geometry_pb2.Vector = None,
    relative: bool = False
) -> TempoMovement.MovementControlService_pb2.PawnMoveToLocationResponse:
    return await _pawn_move_to_location(
        pawn=pawn,
        location=location,
        relative=relative
    )

import TempoCore.Empty_pb2, TempoMovement.MovementControlService_pb2_grpc
async def _rebuild_navigation(
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoMovement.MovementControlService_pb2_grpc.MovementControlServiceStub)
    request = TempoCore.Empty_pb2.Empty(
    )
    return await stub.RebuildNavigation(request)


def rebuild_navigation(
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_rebuild_navigation(
    ))


@awaitable(rebuild_navigation)
async def rebuild_navigation(
) -> TempoCore.Empty_pb2.Empty:
    return await _rebuild_navigation(
    )

