# Warning: Autogenerated code do not edit

from tempo._tempo_context import tempo_context
from tempo import run_async
from curio.meta import awaitable
import asyncio


import TempoWorld.WorldControl_pb2_grpc, TempoCore.Geometry_pb2, TempoWorld.WorldControl_pb2
async def _spawn_actor(
    actor_type: str = '',
    deferred: bool = False,
    transform: TempoCore.Geometry_pb2.Transform = None,
    relative_to_actor: str = ''
) -> TempoWorld.WorldControl_pb2.SpawnActorResponse:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SpawnActorRequest(
        actor_type=actor_type,
        deferred=deferred,
        transform=transform,
        relative_to_actor=relative_to_actor
    )
    return await stub.SpawnActor(request)


def spawn_actor(
    actor_type: str = '',
    deferred: bool = False,
    transform: TempoCore.Geometry_pb2.Transform = None,
    relative_to_actor: str = ''
) -> TempoWorld.WorldControl_pb2.SpawnActorResponse:
    return run_async(_spawn_actor(
        actor_type=actor_type,
        deferred=deferred,
        transform=transform,
        relative_to_actor=relative_to_actor
    ))


@awaitable(spawn_actor)
async def spawn_actor(
    actor_type: str = '',
    deferred: bool = False,
    transform: TempoCore.Geometry_pb2.Transform = None,
    relative_to_actor: str = ''
) -> TempoWorld.WorldControl_pb2.SpawnActorResponse:
    return await _spawn_actor(
        actor_type=actor_type,
        deferred=deferred,
        transform=transform,
        relative_to_actor=relative_to_actor
    )

import TempoWorld.WorldControl_pb2_grpc, TempoWorld.WorldControl_pb2
async def _finish_spawning_actor(
    actor: str = ''
) -> TempoWorld.WorldControl_pb2.FinishSpawningActorResponse:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.FinishSpawningActorRequest(
        actor=actor
    )
    return await stub.FinishSpawningActor(request)


def finish_spawning_actor(
    actor: str = ''
) -> TempoWorld.WorldControl_pb2.FinishSpawningActorResponse:
    return run_async(_finish_spawning_actor(
        actor=actor
    ))


@awaitable(finish_spawning_actor)
async def finish_spawning_actor(
    actor: str = ''
) -> TempoWorld.WorldControl_pb2.FinishSpawningActorResponse:
    return await _finish_spawning_actor(
        actor=actor
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _destroy_actor(
    actor: str = ''
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.DestroyActorRequest(
        actor=actor
    )
    return await stub.DestroyActor(request)


def destroy_actor(
    actor: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_destroy_actor(
        actor=actor
    ))


@awaitable(destroy_actor)
async def destroy_actor(
    actor: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return await _destroy_actor(
        actor=actor
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Geometry_pb2, TempoWorld.WorldControl_pb2
async def _add_component(
    component_type: str = '',
    actor: str = '',
    name: str = '',
    parent: str = '',
    transform: TempoCore.Geometry_pb2.Transform = None,
    socket: str = ''
) -> TempoWorld.WorldControl_pb2.AddComponentResponse:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.AddComponentRequest(
        component_type=component_type,
        actor=actor,
        name=name,
        parent=parent,
        transform=transform,
        socket=socket
    )
    return await stub.AddComponent(request)


def add_component(
    component_type: str = '',
    actor: str = '',
    name: str = '',
    parent: str = '',
    transform: TempoCore.Geometry_pb2.Transform = None,
    socket: str = ''
) -> TempoWorld.WorldControl_pb2.AddComponentResponse:
    return run_async(_add_component(
        component_type=component_type,
        actor=actor,
        name=name,
        parent=parent,
        transform=transform,
        socket=socket
    ))


@awaitable(add_component)
async def add_component(
    component_type: str = '',
    actor: str = '',
    name: str = '',
    parent: str = '',
    transform: TempoCore.Geometry_pb2.Transform = None,
    socket: str = ''
) -> TempoWorld.WorldControl_pb2.AddComponentResponse:
    return await _add_component(
        component_type=component_type,
        actor=actor,
        name=name,
        parent=parent,
        transform=transform,
        socket=socket
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _destroy_component(
    actor: str = '',
    component: str = ''
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.DestroyComponentRequest(
        actor=actor,
        component=component
    )
    return await stub.DestroyComponent(request)


def destroy_component(
    actor: str = '',
    component: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_destroy_component(
        actor=actor,
        component=component
    ))


@awaitable(destroy_component)
async def destroy_component(
    actor: str = '',
    component: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return await _destroy_component(
        actor=actor,
        component=component
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Geometry_pb2, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_actor_transform(
    actor: str = '',
    transform: TempoCore.Geometry_pb2.Transform = None,
    relative_to_actor: str = ''
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetActorTransformRequest(
        actor=actor,
        transform=transform,
        relative_to_actor=relative_to_actor
    )
    return await stub.SetActorTransform(request)


def set_actor_transform(
    actor: str = '',
    transform: TempoCore.Geometry_pb2.Transform = None,
    relative_to_actor: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_actor_transform(
        actor=actor,
        transform=transform,
        relative_to_actor=relative_to_actor
    ))


@awaitable(set_actor_transform)
async def set_actor_transform(
    actor: str = '',
    transform: TempoCore.Geometry_pb2.Transform = None,
    relative_to_actor: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return await _set_actor_transform(
        actor=actor,
        transform=transform,
        relative_to_actor=relative_to_actor
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Geometry_pb2, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_component_transform(
    actor: str = '',
    component: str = '',
    transform: TempoCore.Geometry_pb2.Transform = None,
    relative_to_world: bool = False
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetComponentTransformRequest(
        actor=actor,
        component=component,
        transform=transform,
        relative_to_world=relative_to_world
    )
    return await stub.SetComponentTransform(request)


def set_component_transform(
    actor: str = '',
    component: str = '',
    transform: TempoCore.Geometry_pb2.Transform = None,
    relative_to_world: bool = False
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_component_transform(
        actor=actor,
        component=component,
        transform=transform,
        relative_to_world=relative_to_world
    ))


@awaitable(set_component_transform)
async def set_component_transform(
    actor: str = '',
    component: str = '',
    transform: TempoCore.Geometry_pb2.Transform = None,
    relative_to_world: bool = False
) -> TempoCore.Empty_pb2.Empty:
    return await _set_component_transform(
        actor=actor,
        component=component,
        transform=transform,
        relative_to_world=relative_to_world
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _activate_component(
    actor: str = '',
    component: str = ''
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.ActivateComponentRequest(
        actor=actor,
        component=component
    )
    return await stub.ActivateComponent(request)


def activate_component(
    actor: str = '',
    component: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_activate_component(
        actor=actor,
        component=component
    ))


@awaitable(activate_component)
async def activate_component(
    actor: str = '',
    component: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return await _activate_component(
        actor=actor,
        component=component
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _deactivate_component(
    actor: str = '',
    component: str = ''
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.DeactivateComponentRequest(
        actor=actor,
        component=component
    )
    return await stub.DeactivateComponent(request)


def deactivate_component(
    actor: str = '',
    component: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_deactivate_component(
        actor=actor,
        component=component
    ))


@awaitable(deactivate_component)
async def deactivate_component(
    actor: str = '',
    component: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return await _deactivate_component(
        actor=actor,
        component=component
    )

import TempoWorld.WorldControl_pb2_grpc, TempoWorld.WorldControl_pb2, TempoCore.Empty_pb2
async def _get_all_actors(
) -> TempoWorld.WorldControl_pb2.GetAllActorsResponse:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoCore.Empty_pb2.Empty(
    )
    return await stub.GetAllActors(request)


def get_all_actors(
) -> TempoWorld.WorldControl_pb2.GetAllActorsResponse:
    return run_async(_get_all_actors(
    ))


@awaitable(get_all_actors)
async def get_all_actors(
) -> TempoWorld.WorldControl_pb2.GetAllActorsResponse:
    return await _get_all_actors(
    )

import TempoWorld.WorldControl_pb2_grpc, TempoWorld.WorldControl_pb2
async def _get_all_components(
    actor: str = ''
) -> TempoWorld.WorldControl_pb2.GetAllComponentsResponse:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.GetAllComponentsRequest(
        actor=actor
    )
    return await stub.GetAllComponents(request)


def get_all_components(
    actor: str = ''
) -> TempoWorld.WorldControl_pb2.GetAllComponentsResponse:
    return run_async(_get_all_components(
        actor=actor
    ))


@awaitable(get_all_components)
async def get_all_components(
    actor: str = ''
) -> TempoWorld.WorldControl_pb2.GetAllComponentsResponse:
    return await _get_all_components(
        actor=actor
    )

import TempoWorld.WorldControl_pb2_grpc, TempoWorld.WorldControl_pb2
async def _get_actor_properties(
    actor: str = '',
    include_components: bool = False
) -> TempoWorld.WorldControl_pb2.GetPropertiesResponse:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.GetActorPropertiesRequest(
        actor=actor,
        include_components=include_components
    )
    return await stub.GetActorProperties(request)


def get_actor_properties(
    actor: str = '',
    include_components: bool = False
) -> TempoWorld.WorldControl_pb2.GetPropertiesResponse:
    return run_async(_get_actor_properties(
        actor=actor,
        include_components=include_components
    ))


@awaitable(get_actor_properties)
async def get_actor_properties(
    actor: str = '',
    include_components: bool = False
) -> TempoWorld.WorldControl_pb2.GetPropertiesResponse:
    return await _get_actor_properties(
        actor=actor,
        include_components=include_components
    )

import TempoWorld.WorldControl_pb2_grpc, TempoWorld.WorldControl_pb2
async def _get_component_properties(
    actor: str = '',
    component: str = ''
) -> TempoWorld.WorldControl_pb2.GetPropertiesResponse:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.GetComponentPropertiesRequest(
        actor=actor,
        component=component
    )
    return await stub.GetComponentProperties(request)


def get_component_properties(
    actor: str = '',
    component: str = ''
) -> TempoWorld.WorldControl_pb2.GetPropertiesResponse:
    return run_async(_get_component_properties(
        actor=actor,
        component=component
    ))


@awaitable(get_component_properties)
async def get_component_properties(
    actor: str = '',
    component: str = ''
) -> TempoWorld.WorldControl_pb2.GetPropertiesResponse:
    return await _get_component_properties(
        actor=actor,
        component=component
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_bool_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: bool = False
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetBoolPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        value=value
    )
    return await stub.SetBoolProperty(request)


def set_bool_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: bool = False
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_bool_property(
        actor=actor,
        component=component,
        property=property,
        value=value
    ))


@awaitable(set_bool_property)
async def set_bool_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: bool = False
) -> TempoCore.Empty_pb2.Empty:
    return await _set_bool_property(
        actor=actor,
        component=component,
        property=property,
        value=value
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_string_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: str = ''
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetStringPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        value=value
    )
    return await stub.SetStringProperty(request)


def set_string_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_string_property(
        actor=actor,
        component=component,
        property=property,
        value=value
    ))


@awaitable(set_string_property)
async def set_string_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return await _set_string_property(
        actor=actor,
        component=component,
        property=property,
        value=value
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_enum_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: str = ''
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetEnumPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        value=value
    )
    return await stub.SetEnumProperty(request)


def set_enum_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_enum_property(
        actor=actor,
        component=component,
        property=property,
        value=value
    ))


@awaitable(set_enum_property)
async def set_enum_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return await _set_enum_property(
        actor=actor,
        component=component,
        property=property,
        value=value
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_int_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: int = 0
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetIntPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        value=value
    )
    return await stub.SetIntProperty(request)


def set_int_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: int = 0
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_int_property(
        actor=actor,
        component=component,
        property=property,
        value=value
    ))


@awaitable(set_int_property)
async def set_int_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: int = 0
) -> TempoCore.Empty_pb2.Empty:
    return await _set_int_property(
        actor=actor,
        component=component,
        property=property,
        value=value
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_int64_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: int = 0
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetInt64PropertyRequest(
        actor=actor,
        component=component,
        property=property,
        value=value
    )
    return await stub.SetInt64Property(request)


def set_int64_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: int = 0
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_int64_property(
        actor=actor,
        component=component,
        property=property,
        value=value
    ))


@awaitable(set_int64_property)
async def set_int64_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: int = 0
) -> TempoCore.Empty_pb2.Empty:
    return await _set_int64_property(
        actor=actor,
        component=component,
        property=property,
        value=value
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_float_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: float = 0.0
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetFloatPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        value=value
    )
    return await stub.SetFloatProperty(request)


def set_float_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: float = 0.0
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_float_property(
        actor=actor,
        component=component,
        property=property,
        value=value
    ))


@awaitable(set_float_property)
async def set_float_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: float = 0.0
) -> TempoCore.Empty_pb2.Empty:
    return await _set_float_property(
        actor=actor,
        component=component,
        property=property,
        value=value
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_vector_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    x: float = 0.0,
    y: float = 0.0,
    z: float = 0.0
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetVectorPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        x=x,
        y=y,
        z=z
    )
    return await stub.SetVectorProperty(request)


def set_vector_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    x: float = 0.0,
    y: float = 0.0,
    z: float = 0.0
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_vector_property(
        actor=actor,
        component=component,
        property=property,
        x=x,
        y=y,
        z=z
    ))


@awaitable(set_vector_property)
async def set_vector_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    x: float = 0.0,
    y: float = 0.0,
    z: float = 0.0
) -> TempoCore.Empty_pb2.Empty:
    return await _set_vector_property(
        actor=actor,
        component=component,
        property=property,
        x=x,
        y=y,
        z=z
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_vector2_d_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    x: float = 0.0,
    y: float = 0.0
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetVector2DPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        x=x,
        y=y
    )
    return await stub.SetVector2DProperty(request)


def set_vector2_d_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    x: float = 0.0,
    y: float = 0.0
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_vector2_d_property(
        actor=actor,
        component=component,
        property=property,
        x=x,
        y=y
    ))


@awaitable(set_vector2_d_property)
async def set_vector2_d_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    x: float = 0.0,
    y: float = 0.0
) -> TempoCore.Empty_pb2.Empty:
    return await _set_vector2_d_property(
        actor=actor,
        component=component,
        property=property,
        x=x,
        y=y
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_int_vector_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    x: int = 0,
    y: int = 0,
    z: int = 0
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetIntVectorPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        x=x,
        y=y,
        z=z
    )
    return await stub.SetIntVectorProperty(request)


def set_int_vector_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    x: int = 0,
    y: int = 0,
    z: int = 0
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_int_vector_property(
        actor=actor,
        component=component,
        property=property,
        x=x,
        y=y,
        z=z
    ))


@awaitable(set_int_vector_property)
async def set_int_vector_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    x: int = 0,
    y: int = 0,
    z: int = 0
) -> TempoCore.Empty_pb2.Empty:
    return await _set_int_vector_property(
        actor=actor,
        component=component,
        property=property,
        x=x,
        y=y,
        z=z
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_int_point_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    x: int = 0,
    y: int = 0
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetIntPointPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        x=x,
        y=y
    )
    return await stub.SetIntPointProperty(request)


def set_int_point_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    x: int = 0,
    y: int = 0
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_int_point_property(
        actor=actor,
        component=component,
        property=property,
        x=x,
        y=y
    ))


@awaitable(set_int_point_property)
async def set_int_point_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    x: int = 0,
    y: int = 0
) -> TempoCore.Empty_pb2.Empty:
    return await _set_int_point_property(
        actor=actor,
        component=component,
        property=property,
        x=x,
        y=y
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_rotator_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    r: float = 0.0,
    p: float = 0.0,
    y: float = 0.0
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetRotatorPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        r=r,
        p=p,
        y=y
    )
    return await stub.SetRotatorProperty(request)


def set_rotator_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    r: float = 0.0,
    p: float = 0.0,
    y: float = 0.0
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_rotator_property(
        actor=actor,
        component=component,
        property=property,
        r=r,
        p=p,
        y=y
    ))


@awaitable(set_rotator_property)
async def set_rotator_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    r: float = 0.0,
    p: float = 0.0,
    y: float = 0.0
) -> TempoCore.Empty_pb2.Empty:
    return await _set_rotator_property(
        actor=actor,
        component=component,
        property=property,
        r=r,
        p=p,
        y=y
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_quat_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    x: float = 0.0,
    y: float = 0.0,
    z: float = 0.0,
    w: float = 0.0
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetQuatPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        x=x,
        y=y,
        z=z,
        w=w
    )
    return await stub.SetQuatProperty(request)


def set_quat_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    x: float = 0.0,
    y: float = 0.0,
    z: float = 0.0,
    w: float = 0.0
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_quat_property(
        actor=actor,
        component=component,
        property=property,
        x=x,
        y=y,
        z=z,
        w=w
    ))


@awaitable(set_quat_property)
async def set_quat_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    x: float = 0.0,
    y: float = 0.0,
    z: float = 0.0,
    w: float = 0.0
) -> TempoCore.Empty_pb2.Empty:
    return await _set_quat_property(
        actor=actor,
        component=component,
        property=property,
        x=x,
        y=y,
        z=z,
        w=w
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Geometry_pb2, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_transform_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: TempoCore.Geometry_pb2.Transform = None
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetTransformPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        value=value
    )
    return await stub.SetTransformProperty(request)


def set_transform_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: TempoCore.Geometry_pb2.Transform = None
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_transform_property(
        actor=actor,
        component=component,
        property=property,
        value=value
    ))


@awaitable(set_transform_property)
async def set_transform_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: TempoCore.Geometry_pb2.Transform = None
) -> TempoCore.Empty_pb2.Empty:
    return await _set_transform_property(
        actor=actor,
        component=component,
        property=property,
        value=value
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_color_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    r: int = 0,
    g: int = 0,
    b: int = 0
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetColorPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        r=r,
        g=g,
        b=b
    )
    return await stub.SetColorProperty(request)


def set_color_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    r: int = 0,
    g: int = 0,
    b: int = 0
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_color_property(
        actor=actor,
        component=component,
        property=property,
        r=r,
        g=g,
        b=b
    ))


@awaitable(set_color_property)
async def set_color_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    r: int = 0,
    g: int = 0,
    b: int = 0
) -> TempoCore.Empty_pb2.Empty:
    return await _set_color_property(
        actor=actor,
        component=component,
        property=property,
        r=r,
        g=g,
        b=b
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_class_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: str = ''
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetClassPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        value=value
    )
    return await stub.SetClassProperty(request)


def set_class_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_class_property(
        actor=actor,
        component=component,
        property=property,
        value=value
    ))


@awaitable(set_class_property)
async def set_class_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return await _set_class_property(
        actor=actor,
        component=component,
        property=property,
        value=value
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_asset_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: str = ''
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetAssetPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        value=value
    )
    return await stub.SetAssetProperty(request)


def set_asset_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_asset_property(
        actor=actor,
        component=component,
        property=property,
        value=value
    ))


@awaitable(set_asset_property)
async def set_asset_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return await _set_asset_property(
        actor=actor,
        component=component,
        property=property,
        value=value
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_actor_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: str = ''
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetActorPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        value=value
    )
    return await stub.SetActorProperty(request)


def set_actor_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_actor_property(
        actor=actor,
        component=component,
        property=property,
        value=value
    ))


@awaitable(set_actor_property)
async def set_actor_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return await _set_actor_property(
        actor=actor,
        component=component,
        property=property,
        value=value
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_component_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: str = ''
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetComponentPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        value=value
    )
    return await stub.SetComponentProperty(request)


def set_component_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_component_property(
        actor=actor,
        component=component,
        property=property,
        value=value
    ))


@awaitable(set_component_property)
async def set_component_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    value: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return await _set_component_property(
        actor=actor,
        component=component,
        property=property,
        value=value
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_bool_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: bool = []
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetBoolArrayPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        values=values
    )
    return await stub.SetBoolArrayProperty(request)


def set_bool_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: bool = []
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_bool_array_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    ))


@awaitable(set_bool_array_property)
async def set_bool_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: bool = []
) -> TempoCore.Empty_pb2.Empty:
    return await _set_bool_array_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_string_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetStringArrayPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        values=values
    )
    return await stub.SetStringArrayProperty(request)


def set_string_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_string_array_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    ))


@awaitable(set_string_array_property)
async def set_string_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return await _set_string_array_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_enum_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetEnumArrayPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        values=values
    )
    return await stub.SetEnumArrayProperty(request)


def set_enum_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_enum_array_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    ))


@awaitable(set_enum_array_property)
async def set_enum_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return await _set_enum_array_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_int_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: int = []
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetIntArrayPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        values=values
    )
    return await stub.SetIntArrayProperty(request)


def set_int_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: int = []
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_int_array_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    ))


@awaitable(set_int_array_property)
async def set_int_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: int = []
) -> TempoCore.Empty_pb2.Empty:
    return await _set_int_array_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_int64_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: int = []
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetInt64ArrayPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        values=values
    )
    return await stub.SetInt64ArrayProperty(request)


def set_int64_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: int = []
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_int64_array_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    ))


@awaitable(set_int64_array_property)
async def set_int64_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: int = []
) -> TempoCore.Empty_pb2.Empty:
    return await _set_int64_array_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_float_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: float = []
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetFloatArrayPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        values=values
    )
    return await stub.SetFloatArrayProperty(request)


def set_float_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: float = []
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_float_array_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    ))


@awaitable(set_float_array_property)
async def set_float_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: float = []
) -> TempoCore.Empty_pb2.Empty:
    return await _set_float_array_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_class_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetClassArrayPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        values=values
    )
    return await stub.SetClassArrayProperty(request)


def set_class_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_class_array_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    ))


@awaitable(set_class_array_property)
async def set_class_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return await _set_class_array_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_asset_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetAssetArrayPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        values=values
    )
    return await stub.SetAssetArrayProperty(request)


def set_asset_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_asset_array_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    ))


@awaitable(set_asset_array_property)
async def set_asset_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return await _set_asset_array_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_actor_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetActorArrayPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        values=values
    )
    return await stub.SetActorArrayProperty(request)


def set_actor_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_actor_array_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    ))


@awaitable(set_actor_array_property)
async def set_actor_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return await _set_actor_array_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_component_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetComponentArrayPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        values=values
    )
    return await stub.SetComponentArrayProperty(request)


def set_component_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_component_array_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    ))


@awaitable(set_component_array_property)
async def set_component_array_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return await _set_component_array_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_bool_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: bool = []
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetBoolSetPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        values=values
    )
    return await stub.SetBoolSetProperty(request)


def set_bool_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: bool = []
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_bool_set_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    ))


@awaitable(set_bool_set_property)
async def set_bool_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: bool = []
) -> TempoCore.Empty_pb2.Empty:
    return await _set_bool_set_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_string_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetStringSetPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        values=values
    )
    return await stub.SetStringSetProperty(request)


def set_string_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_string_set_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    ))


@awaitable(set_string_set_property)
async def set_string_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return await _set_string_set_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_enum_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetEnumSetPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        values=values
    )
    return await stub.SetEnumSetProperty(request)


def set_enum_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_enum_set_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    ))


@awaitable(set_enum_set_property)
async def set_enum_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return await _set_enum_set_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_int_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: int = []
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetIntSetPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        values=values
    )
    return await stub.SetIntSetProperty(request)


def set_int_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: int = []
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_int_set_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    ))


@awaitable(set_int_set_property)
async def set_int_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: int = []
) -> TempoCore.Empty_pb2.Empty:
    return await _set_int_set_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_int64_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: int = []
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetInt64SetPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        values=values
    )
    return await stub.SetInt64SetProperty(request)


def set_int64_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: int = []
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_int64_set_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    ))


@awaitable(set_int64_set_property)
async def set_int64_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: int = []
) -> TempoCore.Empty_pb2.Empty:
    return await _set_int64_set_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_float_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: float = []
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetFloatSetPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        values=values
    )
    return await stub.SetFloatSetProperty(request)


def set_float_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: float = []
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_float_set_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    ))


@awaitable(set_float_set_property)
async def set_float_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: float = []
) -> TempoCore.Empty_pb2.Empty:
    return await _set_float_set_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_class_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetClassSetPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        values=values
    )
    return await stub.SetClassSetProperty(request)


def set_class_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_class_set_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    ))


@awaitable(set_class_set_property)
async def set_class_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return await _set_class_set_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_asset_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetAssetSetPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        values=values
    )
    return await stub.SetAssetSetProperty(request)


def set_asset_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_asset_set_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    ))


@awaitable(set_asset_set_property)
async def set_asset_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return await _set_asset_set_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_actor_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetActorSetPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        values=values
    )
    return await stub.SetActorSetProperty(request)


def set_actor_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_actor_set_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    ))


@awaitable(set_actor_set_property)
async def set_actor_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return await _set_actor_set_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _set_component_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetComponentSetPropertyRequest(
        actor=actor,
        component=component,
        property=property,
        values=values
    )
    return await stub.SetComponentSetProperty(request)


def set_component_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_set_component_set_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    ))


@awaitable(set_component_set_property)
async def set_component_set_property(
    actor: str = '',
    component: str = '',
    property: str = '',
    values: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return await _set_component_set_property(
        actor=actor,
        component=component,
        property=property,
        values=values
    )

import TempoWorld.WorldControl_pb2_grpc, TempoWorld.WorldControl_pb2
async def _set_properties(
    ops: TempoWorld.WorldControl_pb2.SetPropertyOp = []
) -> TempoWorld.WorldControl_pb2.SetPropertiesResponse:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.SetPropertiesRequest(
        ops=ops
    )
    return await stub.SetProperties(request)


def set_properties(
    ops: TempoWorld.WorldControl_pb2.SetPropertyOp = []
) -> TempoWorld.WorldControl_pb2.SetPropertiesResponse:
    return run_async(_set_properties(
        ops=ops
    ))


@awaitable(set_properties)
async def set_properties(
    ops: TempoWorld.WorldControl_pb2.SetPropertyOp = []
) -> TempoWorld.WorldControl_pb2.SetPropertiesResponse:
    return await _set_properties(
        ops=ops
    )

import TempoWorld.WorldControl_pb2_grpc, TempoCore.Empty_pb2, TempoWorld.WorldControl_pb2
async def _call_function(
    actor: str = '',
    component: str = '',
    function: str = ''
) -> TempoCore.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
    request = TempoWorld.WorldControl_pb2.CallFunctionRequest(
        actor=actor,
        component=component,
        function=function
    )
    return await stub.CallFunction(request)


def call_function(
    actor: str = '',
    component: str = '',
    function: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return run_async(_call_function(
        actor=actor,
        component=component,
        function=function
    ))


@awaitable(call_function)
async def call_function(
    actor: str = '',
    component: str = '',
    function: str = ''
) -> TempoCore.Empty_pb2.Empty:
    return await _call_function(
        actor=actor,
        component=component,
        function=function
    )

import TempoWorld.WorldState_pb2_grpc, TempoWorld.WorldState_pb2
async def _stream_overlap_events(
    actor: str = ''
) -> TempoWorld.WorldState_pb2.OverlapEventResponse:
    stub = await tempo_context().get_stub(TempoWorld.WorldState_pb2_grpc.WorldStateServiceStub)
    request = TempoWorld.WorldState_pb2.OverlapEventRequest(
        actor=actor
    )
    async for response in stub.StreamOverlapEvents(request):
        yield response


def stream_overlap_events(
    actor: str = ''
) -> TempoWorld.WorldState_pb2.OverlapEventResponse:
    async_gen = _stream_overlap_events(
        actor=actor
    )
    while True:
        try:
            yield run_async(async_gen.__anext__())
        except StopAsyncIteration:
            break


@awaitable(stream_overlap_events)
async def stream_overlap_events(
    actor: str = ''
) -> TempoWorld.WorldState_pb2.OverlapEventResponse:
    async for response in _stream_overlap_events(
        actor=actor
    ):
        yield response

import TempoWorld.WorldState_pb2_grpc, TempoWorld.WorldState_pb2
async def _get_current_actor_state(
    actor: str = '',
    include_hidden_components: bool = False
) -> TempoWorld.WorldState_pb2.ActorState:
    stub = await tempo_context().get_stub(TempoWorld.WorldState_pb2_grpc.WorldStateServiceStub)
    request = TempoWorld.WorldState_pb2.ActorStateRequest(
        actor=actor,
        include_hidden_components=include_hidden_components
    )
    return await stub.GetCurrentActorState(request)


def get_current_actor_state(
    actor: str = '',
    include_hidden_components: bool = False
) -> TempoWorld.WorldState_pb2.ActorState:
    return run_async(_get_current_actor_state(
        actor=actor,
        include_hidden_components=include_hidden_components
    ))


@awaitable(get_current_actor_state)
async def get_current_actor_state(
    actor: str = '',
    include_hidden_components: bool = False
) -> TempoWorld.WorldState_pb2.ActorState:
    return await _get_current_actor_state(
        actor=actor,
        include_hidden_components=include_hidden_components
    )

import TempoWorld.WorldState_pb2_grpc, TempoWorld.WorldState_pb2
async def _stream_actor_state(
    actor: str = '',
    include_hidden_components: bool = False
) -> TempoWorld.WorldState_pb2.ActorState:
    stub = await tempo_context().get_stub(TempoWorld.WorldState_pb2_grpc.WorldStateServiceStub)
    request = TempoWorld.WorldState_pb2.ActorStateRequest(
        actor=actor,
        include_hidden_components=include_hidden_components
    )
    async for response in stub.StreamActorState(request):
        yield response


def stream_actor_state(
    actor: str = '',
    include_hidden_components: bool = False
) -> TempoWorld.WorldState_pb2.ActorState:
    async_gen = _stream_actor_state(
        actor=actor,
        include_hidden_components=include_hidden_components
    )
    while True:
        try:
            yield run_async(async_gen.__anext__())
        except StopAsyncIteration:
            break


@awaitable(stream_actor_state)
async def stream_actor_state(
    actor: str = '',
    include_hidden_components: bool = False
) -> TempoWorld.WorldState_pb2.ActorState:
    async for response in _stream_actor_state(
        actor=actor,
        include_hidden_components=include_hidden_components
    ):
        yield response

import TempoWorld.WorldState_pb2_grpc, TempoWorld.WorldState_pb2
async def _get_current_actor_states_near(
    near_actor: str = '',
    search_radius_m: float = 0.0,
    include_static: bool = False,
    include_hidden_actors: bool = False,
    include_hidden_components: bool = False
) -> TempoWorld.WorldState_pb2.ActorStates:
    stub = await tempo_context().get_stub(TempoWorld.WorldState_pb2_grpc.WorldStateServiceStub)
    request = TempoWorld.WorldState_pb2.ActorStatesNearRequest(
        near_actor=near_actor,
        search_radius_m=search_radius_m,
        include_static=include_static,
        include_hidden_actors=include_hidden_actors,
        include_hidden_components=include_hidden_components
    )
    return await stub.GetCurrentActorStatesNear(request)


def get_current_actor_states_near(
    near_actor: str = '',
    search_radius_m: float = 0.0,
    include_static: bool = False,
    include_hidden_actors: bool = False,
    include_hidden_components: bool = False
) -> TempoWorld.WorldState_pb2.ActorStates:
    return run_async(_get_current_actor_states_near(
        near_actor=near_actor,
        search_radius_m=search_radius_m,
        include_static=include_static,
        include_hidden_actors=include_hidden_actors,
        include_hidden_components=include_hidden_components
    ))


@awaitable(get_current_actor_states_near)
async def get_current_actor_states_near(
    near_actor: str = '',
    search_radius_m: float = 0.0,
    include_static: bool = False,
    include_hidden_actors: bool = False,
    include_hidden_components: bool = False
) -> TempoWorld.WorldState_pb2.ActorStates:
    return await _get_current_actor_states_near(
        near_actor=near_actor,
        search_radius_m=search_radius_m,
        include_static=include_static,
        include_hidden_actors=include_hidden_actors,
        include_hidden_components=include_hidden_components
    )

import TempoWorld.WorldState_pb2_grpc, TempoWorld.WorldState_pb2, TempoCore.Geometry_pb2
async def _get_current_actor_states_near_position(
    position: TempoCore.Geometry_pb2.Vector = None,
    search_radius_m: float = 0.0,
    include_static: bool = False,
    include_hidden_actors: bool = False,
    include_hidden_components: bool = False
) -> TempoWorld.WorldState_pb2.ActorStates:
    stub = await tempo_context().get_stub(TempoWorld.WorldState_pb2_grpc.WorldStateServiceStub)
    request = TempoWorld.WorldState_pb2.ActorStatesNearPositionRequest(
        position=position,
        search_radius_m=search_radius_m,
        include_static=include_static,
        include_hidden_actors=include_hidden_actors,
        include_hidden_components=include_hidden_components
    )
    return await stub.GetCurrentActorStatesNearPosition(request)


def get_current_actor_states_near_position(
    position: TempoCore.Geometry_pb2.Vector = None,
    search_radius_m: float = 0.0,
    include_static: bool = False,
    include_hidden_actors: bool = False,
    include_hidden_components: bool = False
) -> TempoWorld.WorldState_pb2.ActorStates:
    return run_async(_get_current_actor_states_near_position(
        position=position,
        search_radius_m=search_radius_m,
        include_static=include_static,
        include_hidden_actors=include_hidden_actors,
        include_hidden_components=include_hidden_components
    ))


@awaitable(get_current_actor_states_near_position)
async def get_current_actor_states_near_position(
    position: TempoCore.Geometry_pb2.Vector = None,
    search_radius_m: float = 0.0,
    include_static: bool = False,
    include_hidden_actors: bool = False,
    include_hidden_components: bool = False
) -> TempoWorld.WorldState_pb2.ActorStates:
    return await _get_current_actor_states_near_position(
        position=position,
        search_radius_m=search_radius_m,
        include_static=include_static,
        include_hidden_actors=include_hidden_actors,
        include_hidden_components=include_hidden_components
    )

import TempoWorld.WorldState_pb2_grpc, TempoWorld.WorldState_pb2
async def _stream_actor_states_near(
    near_actor: str = '',
    search_radius_m: float = 0.0,
    include_static: bool = False,
    include_hidden_actors: bool = False,
    include_hidden_components: bool = False
) -> TempoWorld.WorldState_pb2.ActorStates:
    stub = await tempo_context().get_stub(TempoWorld.WorldState_pb2_grpc.WorldStateServiceStub)
    request = TempoWorld.WorldState_pb2.ActorStatesNearRequest(
        near_actor=near_actor,
        search_radius_m=search_radius_m,
        include_static=include_static,
        include_hidden_actors=include_hidden_actors,
        include_hidden_components=include_hidden_components
    )
    async for response in stub.StreamActorStatesNear(request):
        yield response


def stream_actor_states_near(
    near_actor: str = '',
    search_radius_m: float = 0.0,
    include_static: bool = False,
    include_hidden_actors: bool = False,
    include_hidden_components: bool = False
) -> TempoWorld.WorldState_pb2.ActorStates:
    async_gen = _stream_actor_states_near(
        near_actor=near_actor,
        search_radius_m=search_radius_m,
        include_static=include_static,
        include_hidden_actors=include_hidden_actors,
        include_hidden_components=include_hidden_components
    )
    while True:
        try:
            yield run_async(async_gen.__anext__())
        except StopAsyncIteration:
            break


@awaitable(stream_actor_states_near)
async def stream_actor_states_near(
    near_actor: str = '',
    search_radius_m: float = 0.0,
    include_static: bool = False,
    include_hidden_actors: bool = False,
    include_hidden_components: bool = False
) -> TempoWorld.WorldState_pb2.ActorStates:
    async for response in _stream_actor_states_near(
        near_actor=near_actor,
        search_radius_m=search_radius_m,
        include_static=include_static,
        include_hidden_actors=include_hidden_actors,
        include_hidden_components=include_hidden_components
    ):
        yield response

import TempoWorld.WorldState_pb2_grpc, TempoWorld.WorldState_pb2, TempoCore.Geometry_pb2
async def _raycast(
    start: TempoCore.Geometry_pb2.Vector = None,
    end: TempoCore.Geometry_pb2.Vector = None,
    collision_channel: TempoWorld.WorldState_pb2.CollisionChannel = 0,
    ignored_actors: str = ''
) -> TempoWorld.WorldState_pb2.RaycastResponse:
    stub = await tempo_context().get_stub(TempoWorld.WorldState_pb2_grpc.WorldStateServiceStub)
    request = TempoWorld.WorldState_pb2.RaycastRequest(
        start=start,
        end=end,
        collision_channel=collision_channel,
        ignored_actors=ignored_actors
    )
    return await stub.Raycast(request)


def raycast(
    start: TempoCore.Geometry_pb2.Vector = None,
    end: TempoCore.Geometry_pb2.Vector = None,
    collision_channel: TempoWorld.WorldState_pb2.CollisionChannel = 0,
    ignored_actors: str = ''
) -> TempoWorld.WorldState_pb2.RaycastResponse:
    return run_async(_raycast(
        start=start,
        end=end,
        collision_channel=collision_channel,
        ignored_actors=ignored_actors
    ))


@awaitable(raycast)
async def raycast(
    start: TempoCore.Geometry_pb2.Vector = None,
    end: TempoCore.Geometry_pb2.Vector = None,
    collision_channel: TempoWorld.WorldState_pb2.CollisionChannel = 0,
    ignored_actors: str = ''
) -> TempoWorld.WorldState_pb2.RaycastResponse:
    return await _raycast(
        start=start,
        end=end,
        collision_channel=collision_channel,
        ignored_actors=ignored_actors
    )

import TempoWorld.WorldControl_pb2, TempoWorld.WorldControl_pb2_grpc


class Batch:
    """Stages property-set operations and submits them in one SetProperties RPC.

    Methods mirror the singular ``set_*_property`` free functions; each appends an op
    to the batch and returns ``self`` for fluent chaining. Call :meth:`execute` (sync)
    or ``await`` :meth:`execute_async` to send.
    """

    def __init__(self):
        self._ops = []

    def set_bool_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        value: bool = False
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            bool_op=TempoWorld.WorldControl_pb2.SetBoolPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                value=value
            )
        ))
        return self

    def set_int_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        value: int = 0
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            int_op=TempoWorld.WorldControl_pb2.SetIntPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                value=value
            )
        ))
        return self

    def set_int64_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        value: int = 0
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            int64_op=TempoWorld.WorldControl_pb2.SetInt64PropertyRequest(
                actor=actor,
                component=component,
                property=property,
                value=value
            )
        ))
        return self

    def set_float_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        value: float = 0.0
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            float_op=TempoWorld.WorldControl_pb2.SetFloatPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                value=value
            )
        ))
        return self

    def set_string_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        value: str = ''
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            string_op=TempoWorld.WorldControl_pb2.SetStringPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                value=value
            )
        ))
        return self

    def set_enum_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        value: str = ''
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            enum_op=TempoWorld.WorldControl_pb2.SetEnumPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                value=value
            )
        ))
        return self

    def set_vector_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        x: float = 0.0,
        y: float = 0.0,
        z: float = 0.0
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            vector_op=TempoWorld.WorldControl_pb2.SetVectorPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                x=x,
                y=y,
                z=z
            )
        ))
        return self

    def set_vector2d_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        x: float = 0.0,
        y: float = 0.0
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            vector2d_op=TempoWorld.WorldControl_pb2.SetVector2DPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                x=x,
                y=y
            )
        ))
        return self

    def set_int_vector_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        x: int = 0,
        y: int = 0,
        z: int = 0
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            int_vector_op=TempoWorld.WorldControl_pb2.SetIntVectorPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                x=x,
                y=y,
                z=z
            )
        ))
        return self

    def set_int_point_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        x: int = 0,
        y: int = 0
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            int_point_op=TempoWorld.WorldControl_pb2.SetIntPointPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                x=x,
                y=y
            )
        ))
        return self

    def set_rotator_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        r: float = 0.0,
        p: float = 0.0,
        y: float = 0.0
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            rotator_op=TempoWorld.WorldControl_pb2.SetRotatorPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                r=r,
                p=p,
                y=y
            )
        ))
        return self

    def set_quat_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        x: float = 0.0,
        y: float = 0.0,
        z: float = 0.0,
        w: float = 0.0
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            quat_op=TempoWorld.WorldControl_pb2.SetQuatPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                x=x,
                y=y,
                z=z,
                w=w
            )
        ))
        return self

    def set_transform_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        value: TempoCore.Geometry_pb2.Transform = None
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            transform_op=TempoWorld.WorldControl_pb2.SetTransformPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                value=value
            )
        ))
        return self

    def set_color_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        r: int = 0,
        g: int = 0,
        b: int = 0
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            color_op=TempoWorld.WorldControl_pb2.SetColorPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                r=r,
                g=g,
                b=b
            )
        ))
        return self

    def set_class_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        value: str = ''
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            class_op=TempoWorld.WorldControl_pb2.SetClassPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                value=value
            )
        ))
        return self

    def set_asset_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        value: str = ''
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            asset_op=TempoWorld.WorldControl_pb2.SetAssetPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                value=value
            )
        ))
        return self

    def set_actor_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        value: str = ''
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            actor_op=TempoWorld.WorldControl_pb2.SetActorPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                value=value
            )
        ))
        return self

    def set_component_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        value: str = ''
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            component_op=TempoWorld.WorldControl_pb2.SetComponentPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                value=value
            )
        ))
        return self

    def set_bool_array_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        values: bool = []
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            bool_array_op=TempoWorld.WorldControl_pb2.SetBoolArrayPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                values=values
            )
        ))
        return self

    def set_string_array_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        values: str = ''
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            string_array_op=TempoWorld.WorldControl_pb2.SetStringArrayPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                values=values
            )
        ))
        return self

    def set_enum_array_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        values: str = ''
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            enum_array_op=TempoWorld.WorldControl_pb2.SetEnumArrayPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                values=values
            )
        ))
        return self

    def set_int_array_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        values: int = []
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            int_array_op=TempoWorld.WorldControl_pb2.SetIntArrayPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                values=values
            )
        ))
        return self

    def set_int64_array_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        values: int = []
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            int64_array_op=TempoWorld.WorldControl_pb2.SetInt64ArrayPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                values=values
            )
        ))
        return self

    def set_float_array_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        values: float = []
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            float_array_op=TempoWorld.WorldControl_pb2.SetFloatArrayPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                values=values
            )
        ))
        return self

    def set_class_array_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        values: str = ''
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            class_array_op=TempoWorld.WorldControl_pb2.SetClassArrayPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                values=values
            )
        ))
        return self

    def set_asset_array_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        values: str = ''
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            asset_array_op=TempoWorld.WorldControl_pb2.SetAssetArrayPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                values=values
            )
        ))
        return self

    def set_actor_array_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        values: str = ''
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            actor_array_op=TempoWorld.WorldControl_pb2.SetActorArrayPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                values=values
            )
        ))
        return self

    def set_component_array_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        values: str = ''
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            component_array_op=TempoWorld.WorldControl_pb2.SetComponentArrayPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                values=values
            )
        ))
        return self

    def set_bool_set_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        values: bool = []
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            bool_set_op=TempoWorld.WorldControl_pb2.SetBoolSetPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                values=values
            )
        ))
        return self

    def set_string_set_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        values: str = ''
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            string_set_op=TempoWorld.WorldControl_pb2.SetStringSetPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                values=values
            )
        ))
        return self

    def set_enum_set_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        values: str = ''
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            enum_set_op=TempoWorld.WorldControl_pb2.SetEnumSetPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                values=values
            )
        ))
        return self

    def set_int_set_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        values: int = []
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            int_set_op=TempoWorld.WorldControl_pb2.SetIntSetPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                values=values
            )
        ))
        return self

    def set_int64_set_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        values: int = []
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            int64_set_op=TempoWorld.WorldControl_pb2.SetInt64SetPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                values=values
            )
        ))
        return self

    def set_float_set_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        values: float = []
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            float_set_op=TempoWorld.WorldControl_pb2.SetFloatSetPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                values=values
            )
        ))
        return self

    def set_class_set_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        values: str = ''
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            class_set_op=TempoWorld.WorldControl_pb2.SetClassSetPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                values=values
            )
        ))
        return self

    def set_asset_set_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        values: str = ''
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            asset_set_op=TempoWorld.WorldControl_pb2.SetAssetSetPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                values=values
            )
        ))
        return self

    def set_actor_set_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        values: str = ''
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            actor_set_op=TempoWorld.WorldControl_pb2.SetActorSetPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                values=values
            )
        ))
        return self

    def set_component_set_property(
        self,
        actor: str = '',
        component: str = '',
        property: str = '',
        values: str = ''
    ) -> 'Batch':
        self._ops.append(TempoWorld.WorldControl_pb2.SetPropertyOp(
            component_set_op=TempoWorld.WorldControl_pb2.SetComponentSetPropertyRequest(
                actor=actor,
                component=component,
                property=property,
                values=values
            )
        ))
        return self

    async def _execute(self) -> TempoWorld.WorldControl_pb2.SetPropertiesResponse:
        stub = await tempo_context().get_stub(TempoWorld.WorldControl_pb2_grpc.WorldControlServiceStub)
        request = TempoWorld.WorldControl_pb2.SetPropertiesRequest(ops=self._ops)
        return await stub.SetProperties(request)

    def execute(self) -> TempoWorld.WorldControl_pb2.SetPropertiesResponse:
        return run_async(self._execute())

    async def execute_async(self) -> TempoWorld.WorldControl_pb2.SetPropertiesResponse:
        return await self._execute()


def batch() -> Batch:
    """Create a new property-set batch builder."""
    return Batch()

