# Warning: Autogenerated code do not edit

from tempo._tempo_context import tempo_context
from tempo import run_async
from curio.meta import awaitable
import asyncio


import VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc, TempoScripting.Empty_pb2, VayuSimCityGeneration.VayuSimCityGeneration_pb2
async def _generate_road_network(
    road_network: VayuSimCityGeneration.VayuSimCityGeneration_pb2.RoadNetwork = None
) -> TempoScripting.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc.VayuSimCityGenerationServiceStub)
    request = VayuSimCityGeneration.VayuSimCityGeneration_pb2.GenerateRoadNetworkRequest(
        road_network=road_network
    )
    return await stub.GenerateRoadNetwork(request)


def generate_road_network(
    road_network: VayuSimCityGeneration.VayuSimCityGeneration_pb2.RoadNetwork = None
) -> TempoScripting.Empty_pb2.Empty:
    return run_async(_generate_road_network(
        road_network=road_network
    ))


@awaitable(generate_road_network)
async def generate_road_network(
    road_network: VayuSimCityGeneration.VayuSimCityGeneration_pb2.RoadNetwork = None
) -> TempoScripting.Empty_pb2.Empty:
    return await _generate_road_network(
        road_network=road_network
    )

import VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc, TempoScripting.Empty_pb2
async def _generate_block_shapes(
) -> TempoScripting.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc.VayuSimCityGenerationServiceStub)
    request = TempoScripting.Empty_pb2.Empty(
    )
    return await stub.GenerateBlockShapes(request)


def generate_block_shapes(
) -> TempoScripting.Empty_pb2.Empty:
    return run_async(_generate_block_shapes(
    ))


@awaitable(generate_block_shapes)
async def generate_block_shapes(
) -> TempoScripting.Empty_pb2.Empty:
    return await _generate_block_shapes(
    )

import VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc, TempoScripting.Empty_pb2, VayuSimCityGeneration.VayuSimCityGeneration_pb2
async def _regenerate_block_shape(
    name: str = ''
) -> TempoScripting.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc.VayuSimCityGenerationServiceStub)
    request = VayuSimCityGeneration.VayuSimCityGeneration_pb2.RegenerateBlockShapeRequest(
        name=name
    )
    return await stub.RegenerateBlockShape(request)


def regenerate_block_shape(
    name: str = ''
) -> TempoScripting.Empty_pb2.Empty:
    return run_async(_regenerate_block_shape(
        name=name
    ))


@awaitable(regenerate_block_shape)
async def regenerate_block_shape(
    name: str = ''
) -> TempoScripting.Empty_pb2.Empty:
    return await _regenerate_block_shape(
        name=name
    )

import VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc, TempoScripting.Empty_pb2, VayuSimCityGeneration.VayuSimCityGeneration_pb2
async def _assign_random_districts(
    districts: VayuSimCityGeneration.VayuSimCityGeneration_pb2.DistrictProportions = None
) -> TempoScripting.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc.VayuSimCityGenerationServiceStub)
    request = VayuSimCityGeneration.VayuSimCityGeneration_pb2.AssignRandomDistrictsRequest(
        districts=districts
    )
    return await stub.AssignRandomDistricts(request)


def assign_random_districts(
    districts: VayuSimCityGeneration.VayuSimCityGeneration_pb2.DistrictProportions = None
) -> TempoScripting.Empty_pb2.Empty:
    return run_async(_assign_random_districts(
        districts=districts
    ))


@awaitable(assign_random_districts)
async def assign_random_districts(
    districts: VayuSimCityGeneration.VayuSimCityGeneration_pb2.DistrictProportions = None
) -> TempoScripting.Empty_pb2.Empty:
    return await _assign_random_districts(
        districts=districts
    )

import VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc, TempoScripting.Empty_pb2, VayuSimCityGeneration.VayuSimCityGeneration_pb2
async def _assign_district(
    block_shape: str = '',
    district: str = ''
) -> TempoScripting.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc.VayuSimCityGenerationServiceStub)
    request = VayuSimCityGeneration.VayuSimCityGeneration_pb2.AssignDistrictRequest(
        block_shape=block_shape,
        district=district
    )
    return await stub.AssignDistrict(request)


def assign_district(
    block_shape: str = '',
    district: str = ''
) -> TempoScripting.Empty_pb2.Empty:
    return run_async(_assign_district(
        block_shape=block_shape,
        district=district
    ))


@awaitable(assign_district)
async def assign_district(
    block_shape: str = '',
    district: str = ''
) -> TempoScripting.Empty_pb2.Empty:
    return await _assign_district(
        block_shape=block_shape,
        district=district
    )

import VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc, TempoScripting.Empty_pb2, VayuSimCityGeneration.VayuSimCityGeneration_pb2
async def _generate_districts(
    district_type: str = '',
    regenerate_block_shapes: bool = False
) -> TempoScripting.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc.VayuSimCityGenerationServiceStub)
    request = VayuSimCityGeneration.VayuSimCityGeneration_pb2.GenerateDistrictsRequest(
        district_type=district_type,
        regenerate_block_shapes=regenerate_block_shapes
    )
    return await stub.GenerateDistricts(request)


def generate_districts(
    district_type: str = '',
    regenerate_block_shapes: bool = False
) -> TempoScripting.Empty_pb2.Empty:
    return run_async(_generate_districts(
        district_type=district_type,
        regenerate_block_shapes=regenerate_block_shapes
    ))


@awaitable(generate_districts)
async def generate_districts(
    district_type: str = '',
    regenerate_block_shapes: bool = False
) -> TempoScripting.Empty_pb2.Empty:
    return await _generate_districts(
        district_type=district_type,
        regenerate_block_shapes=regenerate_block_shapes
    )

import VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc, TempoScripting.Empty_pb2, VayuSimCityGeneration.VayuSimCityGeneration_pb2
async def _generate_district(
    block_shape: str = ''
) -> TempoScripting.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc.VayuSimCityGenerationServiceStub)
    request = VayuSimCityGeneration.VayuSimCityGeneration_pb2.GenerateDistrictRequest(
        block_shape=block_shape
    )
    return await stub.GenerateDistrict(request)


def generate_district(
    block_shape: str = ''
) -> TempoScripting.Empty_pb2.Empty:
    return run_async(_generate_district(
        block_shape=block_shape
    ))


@awaitable(generate_district)
async def generate_district(
    block_shape: str = ''
) -> TempoScripting.Empty_pb2.Empty:
    return await _generate_district(
        block_shape=block_shape
    )

import VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc, TempoScripting.Empty_pb2
async def _demolish_city(
) -> TempoScripting.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc.VayuSimCityGenerationServiceStub)
    request = TempoScripting.Empty_pb2.Empty(
    )
    return await stub.DemolishCity(request)


def demolish_city(
) -> TempoScripting.Empty_pb2.Empty:
    return run_async(_demolish_city(
    ))


@awaitable(demolish_city)
async def demolish_city(
) -> TempoScripting.Empty_pb2.Empty:
    return await _demolish_city(
    )

import VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc, TempoScripting.Empty_pb2
async def _deduplicate_names(
) -> TempoScripting.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc.VayuSimCityGenerationServiceStub)
    request = TempoScripting.Empty_pb2.Empty(
    )
    return await stub.DeduplicateNames(request)


def deduplicate_names(
) -> TempoScripting.Empty_pb2.Empty:
    return run_async(_deduplicate_names(
    ))


@awaitable(deduplicate_names)
async def deduplicate_names(
) -> TempoScripting.Empty_pb2.Empty:
    return await _deduplicate_names(
    )

import VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc, TempoScripting.Empty_pb2, VayuSimCityGeneration.VayuSimCityGeneration_pb2
async def _get_all_roads(
) -> VayuSimCityGeneration.VayuSimCityGeneration_pb2.GetAllRoadsResponse:
    stub = await tempo_context().get_stub(VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc.VayuSimCityGenerationServiceStub)
    request = TempoScripting.Empty_pb2.Empty(
    )
    return await stub.GetAllRoads(request)


def get_all_roads(
) -> VayuSimCityGeneration.VayuSimCityGeneration_pb2.GetAllRoadsResponse:
    return run_async(_get_all_roads(
    ))


@awaitable(get_all_roads)
async def get_all_roads(
) -> VayuSimCityGeneration.VayuSimCityGeneration_pb2.GetAllRoadsResponse:
    return await _get_all_roads(
    )

import VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc, TempoScripting.Empty_pb2, VayuSimCityGeneration.VayuSimCityGeneration_pb2
async def _get_all_intersections(
) -> VayuSimCityGeneration.VayuSimCityGeneration_pb2.GetAllIntersectionsResponse:
    stub = await tempo_context().get_stub(VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc.VayuSimCityGenerationServiceStub)
    request = TempoScripting.Empty_pb2.Empty(
    )
    return await stub.GetAllIntersections(request)


def get_all_intersections(
) -> VayuSimCityGeneration.VayuSimCityGeneration_pb2.GetAllIntersectionsResponse:
    return run_async(_get_all_intersections(
    ))


@awaitable(get_all_intersections)
async def get_all_intersections(
) -> VayuSimCityGeneration.VayuSimCityGeneration_pb2.GetAllIntersectionsResponse:
    return await _get_all_intersections(
    )

import VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc, TempoScripting.Empty_pb2, TempoScripting.Geometry_pb2, VayuSimCityGeneration.VayuSimCityGeneration_pb2
async def _set_intersection_transform(
    name: str = '',
    transform: TempoScripting.Geometry_pb2.Transform = None
) -> TempoScripting.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc.VayuSimCityGenerationServiceStub)
    request = VayuSimCityGeneration.VayuSimCityGeneration_pb2.SetIntersectionTransformRequest(
        name=name,
        transform=transform
    )
    return await stub.SetIntersectionTransform(request)


def set_intersection_transform(
    name: str = '',
    transform: TempoScripting.Geometry_pb2.Transform = None
) -> TempoScripting.Empty_pb2.Empty:
    return run_async(_set_intersection_transform(
        name=name,
        transform=transform
    ))


@awaitable(set_intersection_transform)
async def set_intersection_transform(
    name: str = '',
    transform: TempoScripting.Geometry_pb2.Transform = None
) -> TempoScripting.Empty_pb2.Empty:
    return await _set_intersection_transform(
        name=name,
        transform=transform
    )

import VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc, TempoScripting.Empty_pb2, VayuSimCityGeneration.VayuSimCityGeneration_pb2
async def _regenerate_intersection(
    name: str = ''
) -> TempoScripting.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc.VayuSimCityGenerationServiceStub)
    request = VayuSimCityGeneration.VayuSimCityGeneration_pb2.RegenerateIntersectionRequest(
        name=name
    )
    return await stub.RegenerateIntersection(request)


def regenerate_intersection(
    name: str = ''
) -> TempoScripting.Empty_pb2.Empty:
    return run_async(_regenerate_intersection(
        name=name
    ))


@awaitable(regenerate_intersection)
async def regenerate_intersection(
    name: str = ''
) -> TempoScripting.Empty_pb2.Empty:
    return await _regenerate_intersection(
        name=name
    )

import VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc, TempoScripting.Empty_pb2
async def _remove_orphaned_road_modules(
) -> TempoScripting.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc.VayuSimCityGenerationServiceStub)
    request = TempoScripting.Empty_pb2.Empty(
    )
    return await stub.RemoveOrphanedRoadModules(request)


def remove_orphaned_road_modules(
) -> TempoScripting.Empty_pb2.Empty:
    return run_async(_remove_orphaned_road_modules(
    ))


@awaitable(remove_orphaned_road_modules)
async def remove_orphaned_road_modules(
) -> TempoScripting.Empty_pb2.Empty:
    return await _remove_orphaned_road_modules(
    )

import VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc, TempoScripting.Empty_pb2
async def _remove_landscape_paint_layers(
) -> TempoScripting.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc.VayuSimCityGenerationServiceStub)
    request = TempoScripting.Empty_pb2.Empty(
    )
    return await stub.RemoveLandscapePaintLayers(request)


def remove_landscape_paint_layers(
) -> TempoScripting.Empty_pb2.Empty:
    return run_async(_remove_landscape_paint_layers(
    ))


@awaitable(remove_landscape_paint_layers)
async def remove_landscape_paint_layers(
) -> TempoScripting.Empty_pb2.Empty:
    return await _remove_landscape_paint_layers(
    )

import VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc, TempoScripting.Empty_pb2
async def _activate_selection_ed_mode(
) -> TempoScripting.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc.VayuSimCityGenerationServiceStub)
    request = TempoScripting.Empty_pb2.Empty(
    )
    return await stub.ActivateSelectionEdMode(request)


def activate_selection_ed_mode(
) -> TempoScripting.Empty_pb2.Empty:
    return run_async(_activate_selection_ed_mode(
    ))


@awaitable(activate_selection_ed_mode)
async def activate_selection_ed_mode(
) -> TempoScripting.Empty_pb2.Empty:
    return await _activate_selection_ed_mode(
    )

import VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc, TempoScripting.Empty_pb2
async def _perform_city_b_l_d_migration(
) -> TempoScripting.Empty_pb2.Empty:
    stub = await tempo_context().get_stub(VayuSimCityGeneration.VayuSimCityGeneration_pb2_grpc.VayuSimCityGenerationServiceStub)
    request = TempoScripting.Empty_pb2.Empty(
    )
    return await stub.PerformCityBLDMigration(request)


def perform_city_b_l_d_migration(
) -> TempoScripting.Empty_pb2.Empty:
    return run_async(_perform_city_b_l_d_migration(
    ))


@awaitable(perform_city_b_l_d_migration)
async def perform_city_b_l_d_migration(
) -> TempoScripting.Empty_pb2.Empty:
    return await _perform_city_b_l_d_migration(
    )

