# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from TempoObservableEvents import ObservableEvents_pb2 as TempoObservableEvents_dot_ObservableEvents__pb2


class ObservableEventServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamOverlapEvents = channel.unary_stream(
                '/TempoObservableEvents.ObservableEventService/StreamOverlapEvents',
                request_serializer=TempoObservableEvents_dot_ObservableEvents__pb2.OverlapEventRequest.SerializeToString,
                response_deserializer=TempoObservableEvents_dot_ObservableEvents__pb2.OverlapEventResponse.FromString,
                )


class ObservableEventServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamOverlapEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObservableEventServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamOverlapEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamOverlapEvents,
                    request_deserializer=TempoObservableEvents_dot_ObservableEvents__pb2.OverlapEventRequest.FromString,
                    response_serializer=TempoObservableEvents_dot_ObservableEvents__pb2.OverlapEventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TempoObservableEvents.ObservableEventService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ObservableEventService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamOverlapEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/TempoObservableEvents.ObservableEventService/StreamOverlapEvents',
            TempoObservableEvents_dot_ObservableEvents__pb2.OverlapEventRequest.SerializeToString,
            TempoObservableEvents_dot_ObservableEvents__pb2.OverlapEventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
