// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: TempoLabels/Labels.proto
// Original file comments:
// Copyright Tempo Simulation, LLC. All Rights Reserved
//
#ifndef GRPC_TempoLabels_2fLabels_2eproto__INCLUDED
#define GRPC_TempoLabels_2fLabels_2eproto__INCLUDED

#include "TempoLabels/Labels.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace TempoLabels {

class LabelService final {
 public:
  static constexpr char const* service_full_name() {
    return "TempoLabels.LabelService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetInstanceToSemanticIdMap(::grpc::ClientContext* context, const ::TempoScripting::Empty& request, ::TempoLabels::InstanceToSemanticIdMap* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TempoLabels::InstanceToSemanticIdMap>> AsyncGetInstanceToSemanticIdMap(::grpc::ClientContext* context, const ::TempoScripting::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TempoLabels::InstanceToSemanticIdMap>>(AsyncGetInstanceToSemanticIdMapRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TempoLabels::InstanceToSemanticIdMap>> PrepareAsyncGetInstanceToSemanticIdMap(::grpc::ClientContext* context, const ::TempoScripting::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TempoLabels::InstanceToSemanticIdMap>>(PrepareAsyncGetInstanceToSemanticIdMapRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetInstanceToSemanticIdMap(::grpc::ClientContext* context, const ::TempoScripting::Empty* request, ::TempoLabels::InstanceToSemanticIdMap* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetInstanceToSemanticIdMap(::grpc::ClientContext* context, const ::TempoScripting::Empty* request, ::TempoLabels::InstanceToSemanticIdMap* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::TempoLabels::InstanceToSemanticIdMap>* AsyncGetInstanceToSemanticIdMapRaw(::grpc::ClientContext* context, const ::TempoScripting::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::TempoLabels::InstanceToSemanticIdMap>* PrepareAsyncGetInstanceToSemanticIdMapRaw(::grpc::ClientContext* context, const ::TempoScripting::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetInstanceToSemanticIdMap(::grpc::ClientContext* context, const ::TempoScripting::Empty& request, ::TempoLabels::InstanceToSemanticIdMap* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TempoLabels::InstanceToSemanticIdMap>> AsyncGetInstanceToSemanticIdMap(::grpc::ClientContext* context, const ::TempoScripting::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TempoLabels::InstanceToSemanticIdMap>>(AsyncGetInstanceToSemanticIdMapRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TempoLabels::InstanceToSemanticIdMap>> PrepareAsyncGetInstanceToSemanticIdMap(::grpc::ClientContext* context, const ::TempoScripting::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TempoLabels::InstanceToSemanticIdMap>>(PrepareAsyncGetInstanceToSemanticIdMapRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetInstanceToSemanticIdMap(::grpc::ClientContext* context, const ::TempoScripting::Empty* request, ::TempoLabels::InstanceToSemanticIdMap* response, std::function<void(::grpc::Status)>) override;
      void GetInstanceToSemanticIdMap(::grpc::ClientContext* context, const ::TempoScripting::Empty* request, ::TempoLabels::InstanceToSemanticIdMap* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::TempoLabels::InstanceToSemanticIdMap>* AsyncGetInstanceToSemanticIdMapRaw(::grpc::ClientContext* context, const ::TempoScripting::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::TempoLabels::InstanceToSemanticIdMap>* PrepareAsyncGetInstanceToSemanticIdMapRaw(::grpc::ClientContext* context, const ::TempoScripting::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetInstanceToSemanticIdMap_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetInstanceToSemanticIdMap(::grpc::ServerContext* context, const ::TempoScripting::Empty* request, ::TempoLabels::InstanceToSemanticIdMap* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetInstanceToSemanticIdMap : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetInstanceToSemanticIdMap() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetInstanceToSemanticIdMap() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetInstanceToSemanticIdMap(::grpc::ServerContext* /*context*/, const ::TempoScripting::Empty* /*request*/, ::TempoLabels::InstanceToSemanticIdMap* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetInstanceToSemanticIdMap(::grpc::ServerContext* context, ::TempoScripting::Empty* request, ::grpc::ServerAsyncResponseWriter< ::TempoLabels::InstanceToSemanticIdMap>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetInstanceToSemanticIdMap<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetInstanceToSemanticIdMap : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetInstanceToSemanticIdMap() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::TempoScripting::Empty, ::TempoLabels::InstanceToSemanticIdMap>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::TempoScripting::Empty* request, ::TempoLabels::InstanceToSemanticIdMap* response) { return this->GetInstanceToSemanticIdMap(context, request, response); }));}
    void SetMessageAllocatorFor_GetInstanceToSemanticIdMap(
        ::grpc::MessageAllocator< ::TempoScripting::Empty, ::TempoLabels::InstanceToSemanticIdMap>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::TempoScripting::Empty, ::TempoLabels::InstanceToSemanticIdMap>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetInstanceToSemanticIdMap() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetInstanceToSemanticIdMap(::grpc::ServerContext* /*context*/, const ::TempoScripting::Empty* /*request*/, ::TempoLabels::InstanceToSemanticIdMap* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetInstanceToSemanticIdMap(
      ::grpc::CallbackServerContext* /*context*/, const ::TempoScripting::Empty* /*request*/, ::TempoLabels::InstanceToSemanticIdMap* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetInstanceToSemanticIdMap<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetInstanceToSemanticIdMap : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetInstanceToSemanticIdMap() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetInstanceToSemanticIdMap() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetInstanceToSemanticIdMap(::grpc::ServerContext* /*context*/, const ::TempoScripting::Empty* /*request*/, ::TempoLabels::InstanceToSemanticIdMap* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetInstanceToSemanticIdMap : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetInstanceToSemanticIdMap() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetInstanceToSemanticIdMap() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetInstanceToSemanticIdMap(::grpc::ServerContext* /*context*/, const ::TempoScripting::Empty* /*request*/, ::TempoLabels::InstanceToSemanticIdMap* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetInstanceToSemanticIdMap(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetInstanceToSemanticIdMap : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetInstanceToSemanticIdMap() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetInstanceToSemanticIdMap(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetInstanceToSemanticIdMap() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetInstanceToSemanticIdMap(::grpc::ServerContext* /*context*/, const ::TempoScripting::Empty* /*request*/, ::TempoLabels::InstanceToSemanticIdMap* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetInstanceToSemanticIdMap(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetInstanceToSemanticIdMap : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetInstanceToSemanticIdMap() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::TempoScripting::Empty, ::TempoLabels::InstanceToSemanticIdMap>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::TempoScripting::Empty, ::TempoLabels::InstanceToSemanticIdMap>* streamer) {
                       return this->StreamedGetInstanceToSemanticIdMap(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetInstanceToSemanticIdMap() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetInstanceToSemanticIdMap(::grpc::ServerContext* /*context*/, const ::TempoScripting::Empty* /*request*/, ::TempoLabels::InstanceToSemanticIdMap* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetInstanceToSemanticIdMap(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::TempoScripting::Empty,::TempoLabels::InstanceToSemanticIdMap>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetInstanceToSemanticIdMap<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetInstanceToSemanticIdMap<Service > StreamedService;
};

}  // namespace TempoLabels


#endif  // GRPC_TempoLabels_2fLabels_2eproto__INCLUDED
