// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: TempoAgentsEditor/TempoAgentsEditor.proto
// Original file comments:
// Copyright Tempo Simulation, LLC. All Rights Reserved.
//
#ifndef GRPC_TempoAgentsEditor_2fTempoAgentsEditor_2eproto__INCLUDED
#define GRPC_TempoAgentsEditor_2fTempoAgentsEditor_2eproto__INCLUDED

#include "TempoAgentsEditor/TempoAgentsEditor.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace TempoAgentsEditor {

class TempoAgentsEditorService final {
 public:
  static constexpr char const* service_full_name() {
    return "TempoAgentsEditor.TempoAgentsEditorService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RunTempoZoneGraphBuilderPipeline(::grpc::ClientContext* context, const ::TempoScripting::Empty& request, ::TempoAgentsEditor::PipelineResult* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TempoAgentsEditor::PipelineResult>> AsyncRunTempoZoneGraphBuilderPipeline(::grpc::ClientContext* context, const ::TempoScripting::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TempoAgentsEditor::PipelineResult>>(AsyncRunTempoZoneGraphBuilderPipelineRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TempoAgentsEditor::PipelineResult>> PrepareAsyncRunTempoZoneGraphBuilderPipeline(::grpc::ClientContext* context, const ::TempoScripting::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TempoAgentsEditor::PipelineResult>>(PrepareAsyncRunTempoZoneGraphBuilderPipelineRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void RunTempoZoneGraphBuilderPipeline(::grpc::ClientContext* context, const ::TempoScripting::Empty* request, ::TempoAgentsEditor::PipelineResult* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RunTempoZoneGraphBuilderPipeline(::grpc::ClientContext* context, const ::TempoScripting::Empty* request, ::TempoAgentsEditor::PipelineResult* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::TempoAgentsEditor::PipelineResult>* AsyncRunTempoZoneGraphBuilderPipelineRaw(::grpc::ClientContext* context, const ::TempoScripting::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::TempoAgentsEditor::PipelineResult>* PrepareAsyncRunTempoZoneGraphBuilderPipelineRaw(::grpc::ClientContext* context, const ::TempoScripting::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RunTempoZoneGraphBuilderPipeline(::grpc::ClientContext* context, const ::TempoScripting::Empty& request, ::TempoAgentsEditor::PipelineResult* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TempoAgentsEditor::PipelineResult>> AsyncRunTempoZoneGraphBuilderPipeline(::grpc::ClientContext* context, const ::TempoScripting::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TempoAgentsEditor::PipelineResult>>(AsyncRunTempoZoneGraphBuilderPipelineRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TempoAgentsEditor::PipelineResult>> PrepareAsyncRunTempoZoneGraphBuilderPipeline(::grpc::ClientContext* context, const ::TempoScripting::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TempoAgentsEditor::PipelineResult>>(PrepareAsyncRunTempoZoneGraphBuilderPipelineRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RunTempoZoneGraphBuilderPipeline(::grpc::ClientContext* context, const ::TempoScripting::Empty* request, ::TempoAgentsEditor::PipelineResult* response, std::function<void(::grpc::Status)>) override;
      void RunTempoZoneGraphBuilderPipeline(::grpc::ClientContext* context, const ::TempoScripting::Empty* request, ::TempoAgentsEditor::PipelineResult* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::TempoAgentsEditor::PipelineResult>* AsyncRunTempoZoneGraphBuilderPipelineRaw(::grpc::ClientContext* context, const ::TempoScripting::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::TempoAgentsEditor::PipelineResult>* PrepareAsyncRunTempoZoneGraphBuilderPipelineRaw(::grpc::ClientContext* context, const ::TempoScripting::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RunTempoZoneGraphBuilderPipeline_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RunTempoZoneGraphBuilderPipeline(::grpc::ServerContext* context, const ::TempoScripting::Empty* request, ::TempoAgentsEditor::PipelineResult* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RunTempoZoneGraphBuilderPipeline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RunTempoZoneGraphBuilderPipeline() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RunTempoZoneGraphBuilderPipeline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunTempoZoneGraphBuilderPipeline(::grpc::ServerContext* /*context*/, const ::TempoScripting::Empty* /*request*/, ::TempoAgentsEditor::PipelineResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRunTempoZoneGraphBuilderPipeline(::grpc::ServerContext* context, ::TempoScripting::Empty* request, ::grpc::ServerAsyncResponseWriter< ::TempoAgentsEditor::PipelineResult>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RunTempoZoneGraphBuilderPipeline<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RunTempoZoneGraphBuilderPipeline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RunTempoZoneGraphBuilderPipeline() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::TempoScripting::Empty, ::TempoAgentsEditor::PipelineResult>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::TempoScripting::Empty* request, ::TempoAgentsEditor::PipelineResult* response) { return this->RunTempoZoneGraphBuilderPipeline(context, request, response); }));}
    void SetMessageAllocatorFor_RunTempoZoneGraphBuilderPipeline(
        ::grpc::MessageAllocator< ::TempoScripting::Empty, ::TempoAgentsEditor::PipelineResult>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::TempoScripting::Empty, ::TempoAgentsEditor::PipelineResult>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RunTempoZoneGraphBuilderPipeline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunTempoZoneGraphBuilderPipeline(::grpc::ServerContext* /*context*/, const ::TempoScripting::Empty* /*request*/, ::TempoAgentsEditor::PipelineResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RunTempoZoneGraphBuilderPipeline(
      ::grpc::CallbackServerContext* /*context*/, const ::TempoScripting::Empty* /*request*/, ::TempoAgentsEditor::PipelineResult* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RunTempoZoneGraphBuilderPipeline<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RunTempoZoneGraphBuilderPipeline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RunTempoZoneGraphBuilderPipeline() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RunTempoZoneGraphBuilderPipeline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunTempoZoneGraphBuilderPipeline(::grpc::ServerContext* /*context*/, const ::TempoScripting::Empty* /*request*/, ::TempoAgentsEditor::PipelineResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RunTempoZoneGraphBuilderPipeline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RunTempoZoneGraphBuilderPipeline() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RunTempoZoneGraphBuilderPipeline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunTempoZoneGraphBuilderPipeline(::grpc::ServerContext* /*context*/, const ::TempoScripting::Empty* /*request*/, ::TempoAgentsEditor::PipelineResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRunTempoZoneGraphBuilderPipeline(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RunTempoZoneGraphBuilderPipeline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RunTempoZoneGraphBuilderPipeline() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RunTempoZoneGraphBuilderPipeline(context, request, response); }));
    }
    ~WithRawCallbackMethod_RunTempoZoneGraphBuilderPipeline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunTempoZoneGraphBuilderPipeline(::grpc::ServerContext* /*context*/, const ::TempoScripting::Empty* /*request*/, ::TempoAgentsEditor::PipelineResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RunTempoZoneGraphBuilderPipeline(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RunTempoZoneGraphBuilderPipeline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RunTempoZoneGraphBuilderPipeline() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::TempoScripting::Empty, ::TempoAgentsEditor::PipelineResult>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::TempoScripting::Empty, ::TempoAgentsEditor::PipelineResult>* streamer) {
                       return this->StreamedRunTempoZoneGraphBuilderPipeline(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RunTempoZoneGraphBuilderPipeline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RunTempoZoneGraphBuilderPipeline(::grpc::ServerContext* /*context*/, const ::TempoScripting::Empty* /*request*/, ::TempoAgentsEditor::PipelineResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRunTempoZoneGraphBuilderPipeline(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::TempoScripting::Empty,::TempoAgentsEditor::PipelineResult>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RunTempoZoneGraphBuilderPipeline<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RunTempoZoneGraphBuilderPipeline<Service > StreamedService;
};

}  // namespace TempoAgentsEditor


#endif  // GRPC_TempoAgentsEditor_2fTempoAgentsEditor_2eproto__INCLUDED
