// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TempoAgentsEditor/TempoAgentsEditor.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_TempoAgentsEditor_2fTempoAgentsEditor_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_TempoAgentsEditor_2fTempoAgentsEditor_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "TempoScripting/Empty.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_TempoAgentsEditor_2fTempoAgentsEditor_2eproto TEMPOAGENTSEDITOR_API

namespace google {
namespace protobuf_tempo {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf_tempo
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TEMPOAGENTSEDITOR_API TableStruct_TempoAgentsEditor_2fTempoAgentsEditor_2eproto {
  static const ::uint32_t offsets[];
};
TEMPOAGENTSEDITOR_API extern const ::google::protobuf_tempo::internal::DescriptorTable
    descriptor_table_TempoAgentsEditor_2fTempoAgentsEditor_2eproto;
namespace TempoAgentsEditor {
class PipelineResult;
struct PipelineResultDefaultTypeInternal;
TEMPOAGENTSEDITOR_API extern PipelineResultDefaultTypeInternal _PipelineResult_default_instance_;
}  // namespace TempoAgentsEditor
namespace google {
namespace protobuf_tempo {
}  // namespace protobuf_tempo
}  // namespace google

namespace TempoAgentsEditor {

// ===================================================================


// -------------------------------------------------------------------

class TEMPOAGENTSEDITOR_API PipelineResult final :
    public ::google::protobuf_tempo::Message /* @@protoc_insertion_point(class_definition:TempoAgentsEditor.PipelineResult) */ {
 public:
  inline PipelineResult() : PipelineResult(nullptr) {}
  ~PipelineResult() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR PipelineResult(::google::protobuf_tempo::internal::ConstantInitialized);

  inline PipelineResult(const PipelineResult& from)
      : PipelineResult(nullptr, from) {}
  PipelineResult(PipelineResult&& from) noexcept
    : PipelineResult() {
    *this = ::std::move(from);
  }

  inline PipelineResult& operator=(const PipelineResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline PipelineResult& operator=(PipelineResult&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf_tempo::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf_tempo::UnknownFieldSet>(::google::protobuf_tempo::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf_tempo::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf_tempo::UnknownFieldSet>();
  }

  static const ::google::protobuf_tempo::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf_tempo::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf_tempo::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PipelineResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const PipelineResult* internal_default_instance() {
    return reinterpret_cast<const PipelineResult*>(
               &_PipelineResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PipelineResult& a, PipelineResult& b) {
    a.Swap(&b);
  }
  inline void Swap(PipelineResult* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf_tempo::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PipelineResult* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PipelineResult* New(::google::protobuf_tempo::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PipelineResult>(arena);
  }
  using ::google::protobuf_tempo::Message::CopyFrom;
  void CopyFrom(const PipelineResult& from);
  using ::google::protobuf_tempo::Message::MergeFrom;
  void MergeFrom( const PipelineResult& from) {
    PipelineResult::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf_tempo::Message& to_msg, const ::google::protobuf_tempo::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf_tempo::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf_tempo::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf_tempo::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf_tempo::Arena* arena);
  void SharedDtor();
  void InternalSwap(PipelineResult* other);

  private:
  friend class ::google::protobuf_tempo::internal::AnyMetadata;
  static ::absl_tempo::string_view FullMessageName() {
    return "TempoAgentsEditor.PipelineResult";
  }
  protected:
  explicit PipelineResult(::google::protobuf_tempo::Arena* arena);
  PipelineResult(::google::protobuf_tempo::Arena* arena, const PipelineResult& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf_tempo::Message::ClassData*GetClassData() const final;

  ::google::protobuf_tempo::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
  };
  // bool success = 1;
  void clear_success() ;
  bool success() const;
  void set_success(bool value);

  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);

  public:
  // @@protoc_insertion_point(class_scope:TempoAgentsEditor.PipelineResult)
 private:
  class _Internal;

  friend class ::google::protobuf_tempo::internal::TcParser;
  static const ::google::protobuf_tempo::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf_tempo::MessageLite;
  friend class ::google::protobuf_tempo::Arena;
  template <typename T>
  friend class ::google::protobuf_tempo::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct TEMPOAGENTSEDITOR_API Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf_tempo::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf_tempo::internal::InternalVisibility visibility,
                              ::google::protobuf_tempo::Arena* arena);
        inline explicit Impl_(::google::protobuf_tempo::internal::InternalVisibility visibility,
                              ::google::protobuf_tempo::Arena* arena, const Impl_& from);
    bool success_;
    mutable ::google::protobuf_tempo::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_TempoAgentsEditor_2fTempoAgentsEditor_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PipelineResult

// bool success = 1;
inline void PipelineResult::clear_success() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.success_ = false;
}
inline bool PipelineResult::success() const {
  // @@protoc_insertion_point(field_get:TempoAgentsEditor.PipelineResult.success)
  return _internal_success();
}
inline void PipelineResult::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:TempoAgentsEditor.PipelineResult.success)
}
inline bool PipelineResult::_internal_success() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.success_;
}
inline void PipelineResult::_internal_set_success(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.success_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace TempoAgentsEditor


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_TempoAgentsEditor_2fTempoAgentsEditor_2eproto_2epb_2eh
