// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: TempoAgentsEditor/TempoAgentsEditor.proto

#include "TempoAgentsEditor/TempoAgentsEditor.pb.h"
#include "TempoAgentsEditor/TempoAgentsEditor.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace TempoAgentsEditor {

static const char* TempoAgentsEditorService_method_names[] = {
  "/TempoAgentsEditor.TempoAgentsEditorService/RunTempoZoneGraphBuilderPipeline",
};

std::unique_ptr< TempoAgentsEditorService::Stub> TempoAgentsEditorService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TempoAgentsEditorService::Stub> stub(new TempoAgentsEditorService::Stub(channel, options));
  return stub;
}

TempoAgentsEditorService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RunTempoZoneGraphBuilderPipeline_(TempoAgentsEditorService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TempoAgentsEditorService::Stub::RunTempoZoneGraphBuilderPipeline(::grpc::ClientContext* context, const ::TempoScripting::Empty& request, ::TempoAgentsEditor::PipelineResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::TempoScripting::Empty, ::TempoAgentsEditor::PipelineResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RunTempoZoneGraphBuilderPipeline_, context, request, response);
}

void TempoAgentsEditorService::Stub::async::RunTempoZoneGraphBuilderPipeline(::grpc::ClientContext* context, const ::TempoScripting::Empty* request, ::TempoAgentsEditor::PipelineResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::TempoScripting::Empty, ::TempoAgentsEditor::PipelineResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RunTempoZoneGraphBuilderPipeline_, context, request, response, std::move(f));
}

void TempoAgentsEditorService::Stub::async::RunTempoZoneGraphBuilderPipeline(::grpc::ClientContext* context, const ::TempoScripting::Empty* request, ::TempoAgentsEditor::PipelineResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RunTempoZoneGraphBuilderPipeline_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TempoAgentsEditor::PipelineResult>* TempoAgentsEditorService::Stub::PrepareAsyncRunTempoZoneGraphBuilderPipelineRaw(::grpc::ClientContext* context, const ::TempoScripting::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TempoAgentsEditor::PipelineResult, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RunTempoZoneGraphBuilderPipeline_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TempoAgentsEditor::PipelineResult>* TempoAgentsEditorService::Stub::AsyncRunTempoZoneGraphBuilderPipelineRaw(::grpc::ClientContext* context, const ::TempoScripting::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRunTempoZoneGraphBuilderPipelineRaw(context, request, cq);
  result->StartCall();
  return result;
}

TempoAgentsEditorService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TempoAgentsEditorService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TempoAgentsEditorService::Service, ::TempoScripting::Empty, ::TempoAgentsEditor::PipelineResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TempoAgentsEditorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::TempoScripting::Empty* req,
             ::TempoAgentsEditor::PipelineResult* resp) {
               return service->RunTempoZoneGraphBuilderPipeline(ctx, req, resp);
             }, this)));
}

TempoAgentsEditorService::Service::~Service() {
}

::grpc::Status TempoAgentsEditorService::Service::RunTempoZoneGraphBuilderPipeline(::grpc::ServerContext* context, const ::TempoScripting::Empty* request, ::TempoAgentsEditor::PipelineResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace TempoAgentsEditor

