# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TempoSensors/Sensors.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from TempoCamera import Camera_pb2 as TempoCamera_dot_Camera__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aTempoSensors/Sensors.proto\x12\x0cTempoSensors\x1a\x18TempoCamera/Camera.proto\"w\n\x10SensorDescriptor\x12\r\n\x05owner\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04rate\x18\x03 \x01(\x02\x12\x38\n\x11measurement_types\x18\x04 \x03(\x0e\x32\x1d.TempoSensors.MeasurementType\"\x19\n\x17\x41vailableSensorsRequest\"U\n\x18\x41vailableSensorsResponse\x12\x39\n\x11\x61vailable_sensors\x18\x01 \x03(\x0b\x32\x1e.TempoSensors.SensorDescriptor*D\n\x0fMeasurementType\x12\x0f\n\x0b\x43OLOR_IMAGE\x10\x00\x12\x0f\n\x0b\x44\x45PTH_IMAGE\x10\x01\x12\x0f\n\x0bLABEL_IMAGE\x10\x02\x32\xe5\x02\n\rSensorService\x12\x64\n\x13GetAvailableSensors\x12%.TempoSensors.AvailableSensorsRequest\x1a&.TempoSensors.AvailableSensorsResponse\x12N\n\x11StreamColorImages\x12\x1e.TempoCamera.ColorImageRequest\x1a\x17.TempoCamera.ColorImage0\x01\x12N\n\x11StreamDepthImages\x12\x1e.TempoCamera.DepthImageRequest\x1a\x17.TempoCamera.DepthImage0\x01\x12N\n\x11StreamLabelImages\x12\x1e.TempoCamera.LabelImageRequest\x1a\x17.TempoCamera.LabelImage0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TempoSensors.Sensors_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MEASUREMENTTYPE']._serialized_start=305
  _globals['_MEASUREMENTTYPE']._serialized_end=373
  _globals['_SENSORDESCRIPTOR']._serialized_start=70
  _globals['_SENSORDESCRIPTOR']._serialized_end=189
  _globals['_AVAILABLESENSORSREQUEST']._serialized_start=191
  _globals['_AVAILABLESENSORSREQUEST']._serialized_end=216
  _globals['_AVAILABLESENSORSRESPONSE']._serialized_start=218
  _globals['_AVAILABLESENSORSRESPONSE']._serialized_end=303
  _globals['_SENSORSERVICE']._serialized_start=376
  _globals['_SENSORSERVICE']._serialized_end=733
# @@protoc_insertion_point(module_scope)
