# Copyright Tempo Simulation, LLC. All Rights Reserved

import importlib
import jinja2
import os
import sys
from pathlib import Path
from typing import List

from prebuild_cache import PrebuildCache, find_files_filtered

from gen_common import (
    gather_enums,
    gather_messages,
    gather_services,
    pascal_to_snake,
)


def generate_tempo_api(root_dir):
    all_enums = {}
    all_messages = {}
    all_services = {}
    potentially_stale_files = set([name for name in os.listdir(root_dir) 
                                   if os.path.isfile(os.path.join(root_dir, name))])
    # Non-generated files
    potentially_stale_files.remove(".gitignore")
    potentially_stale_files.remove("_tempo_context.py")
    potentially_stale_files.remove("TempoImageUtils.py")
    potentially_stale_files.remove("TempoLidarUtils.py")
    potentially_stale_files.remove("__init__.py")
    tempo_module_names = [name for name in os.listdir(root_dir) if os.path.isdir(os.path.join(root_dir, name))]
    for tempo_module_name in tempo_module_names:
        tempo_module_root = os.path.join(root_dir, tempo_module_name)
        contains_services = False
        for path, _, files in os.walk(tempo_module_root):
            for filename in files:
                if filename.endswith("_pb2.py"):
                    file_path = os.path.join(path, filename)
                    rel_path = os.path.relpath(file_path, tempo_module_root)
                    module_name = "{}.{}".format(
                        tempo_module_name, os.path.splitext(rel_path)[0].replace(os.sep, '.'))
                    module = importlib.import_module(module_name)
                    if hasattr(module, "DESCRIPTOR"):
                        module_descriptor = module.DESCRIPTOR
                        all_enums = all_enums | gather_enums(module_name, module_descriptor)
                        all_messages = all_messages | gather_messages(module_name, module_descriptor)
                        services = gather_services(module_name, module_descriptor)
                        if len(services) > 0:
                            contains_services = True
                        module_rpcs = set()
                        for service in services.values():
                            for rpc in service.rpcs:
                                rpc_name = rpc.name
                                if rpc_name in module_rpcs:
                                    raise Exception(f"Module {tempo_module_name} has two rpcs named {rpc_name}. "
                                                    f"This is not allowed! Please rename one.")
                                module_rpcs.add(rpc_name)
                        all_services = all_services | services
        if contains_services:
            output_file = f"{pascal_to_snake(tempo_module_name)}.py"
            potentially_stale_files.discard(output_file)
            with open(os.path.join(root_dir, output_file), 'w') as f:
                f.write("# Warning: Autogenerated code do not edit\n\n")
                f.write("from tempo._tempo_context import tempo_context\n")
                f.write("from tempo import run_async\n")
                f.write("from curio.meta import awaitable\n")
                f.write("import asyncio\n")
                f.write("\n\n")
                
    for stale_file in potentially_stale_files:
        os.remove(os.path.join(root_dir, stale_file))

    # The Protobuf-provided "descriptor" objects use the Protobuf names for classes, but we want the names of the
    # generated Python classes. The all_* dictionaries can provide that mapping, so we go through all the messages
    # once more to "resolve" all the types of message fields here.
    for tempo_message_descriptor in all_messages.values():
        tempo_message_descriptor.resolve_names(all_messages | all_enums)

    # Every RPC gets sync and async versions. The correct one will automatically be chosen by context.
    simple_rpc_template = \
        "import " \
        "{% for import in imports %}" \
        "{{ import }}{% if not loop.last %}, {% endif %}" \
        "{% endfor %}" \
        "\n" \
        "async def _{{ name }}(\n" \
        "{% for field in request.fields %}" \
        "    {{ field.name }}: {{ field.field_type }} = {{ field.default }}{% if not loop.last %},{% endif %}\n" \
        "{% endfor %}" \
        ") -> {{ response.full_name }}:\n" \
        "    stub = await tempo_context().get_stub({{ service.module_name }}_grpc.{{ service.object_name }}Stub)\n" \
        "    request = {{ request.full_name }}(\n" \
        "{% for field in request.fields %}" \
        "        {{ field.name }}={{ field.name }}{% if not loop.last %},{% endif %}\n" \
        "{% endfor %}" \
        "    )\n" \
        "    return await stub.{{ rpc.name }}(request)\n" \
        "\n\n" \
        "def {{ name }}(\n" \
        "{% for field in request.fields %}" \
        "    {{ field.name }}: {{ field.field_type }} = {{ field.default }}{% if not loop.last %},{% endif %}\n" \
        "{% endfor %}" \
        ") -> {{ response.full_name }}:\n" \
        "    return run_async(_{{ name }}(\n" \
        "{% for field in request.fields %}" \
        "        {{ field.name }}={{ field.name }}{% if not loop.last %},{% endif %}\n" \
        "{% endfor %}" \
        "    ))\n" \
        "\n\n" \
        "@awaitable({{ name }})\n" \
        "async def {{ name }}(\n" \
        "{% for field in request.fields %}" \
        "    {{ field.name }}: {{ field.field_type }} = {{ field.default }}{% if not loop.last %},{% endif %}\n" \
        "{% endfor %}" \
        ") -> {{ response.full_name }}:\n" \
        "    return await _{{ name }}(\n" \
        "{% for field in request.fields %}" \
        "        {{ field.name }}={{ field.name }}{% if not loop.last %},{% endif %}\n" \
        "{% endfor %}" \
        "    )\n" \
        "\n\n" \

    streaming_rpc_template = \
        "import " \
        "{% for import in imports %}" \
        "{{ import }}{% if not loop.last %}, {% endif %}" \
        "{% endfor %}" \
        "\n" \
        "async def _{{ name }}(\n" \
        "{% for field in request.fields %}" \
        "    {{ field.name }}: {{ field.field_type }} = {{ field.default }}{% if not loop.last %},{% endif %}\n" \
        "{% endfor %}" \
        ") -> {{ response.full_name }}:\n" \
        "    stub = await tempo_context().get_stub({{ service.module_name }}_grpc.{{ service.object_name }}Stub)\n" \
        "    request = {{ request.full_name }}(\n" \
        "{% for field in request.fields %}" \
        "        {{ field.name }}={{ field.name }}{% if not loop.last %},{% endif %}\n" \
        "{% endfor %}" \
        "    )\n" \
        "    async for response in stub.{{ rpc.name }}(request):\n" \
        "        yield response\n" \
        "\n\n" \
        "def {{ name }}(\n" \
        "{% for field in request.fields %}" \
        "    {{ field.name }}: {{ field.field_type }} = {{ field.default }}{% if not loop.last %},{% endif %}\n" \
        "{% endfor %}" \
        ") -> {{ response.full_name }}:\n" \
        "    async_gen = _{{ name }}(\n" \
        "{% for field in request.fields %}" \
        "        {{ field.name }}={{ field.name }}{% if not loop.last %},{% endif %}\n" \
        "{% endfor %}" \
        "    )\n" \
        "    while True:\n" \
        "        try:\n" \
        "            yield run_async(async_gen.__anext__())\n" \
        "        except StopAsyncIteration:\n" \
        "            break\n" \
        "\n\n" \
        "@awaitable({{ name }})\n" \
        "async def {{ name }}(\n" \
        "{% for field in request.fields %}" \
        "    {{ field.name }}: {{ field.field_type }} = {{ field.default }}{% if not loop.last %},{% endif %}\n" \
        "{% endfor %}" \
        ") -> {{ response.full_name }}:\n" \
        "    async for response in _{{ name }}(\n" \
        "{% for field in request.fields %}" \
        "        {{ field.name }}={{ field.name }}{% if not loop.last %},{% endif %}\n" \
        "{% endfor %}" \
        "    ):\n" \
        "        yield response\n" \
        "\n\n" \

    # Template for a Batch class that wraps a oneof-of-Set*PropertyRequest into
    # a fluent builder, so users don't have to construct SetPropertyOp messages
    # themselves. One method per oneof variant; execute() / execute_async() send
    # one SetProperties RPC for the staged ops.
    batch_template = \
        "import " \
        "{% for import in imports %}" \
        "{{ import }}{% if not loop.last %}, {% endif %}" \
        "{% endfor %}" \
        "\n\n\n" \
        "class Batch:\n" \
        '    """Stages property-set operations and submits them in one SetProperties RPC.\n' \
        "\n" \
        "    Methods mirror the singular ``set_*_property`` free functions; each appends an op\n" \
        "    to the batch and returns ``self`` for fluent chaining. Call :meth:`execute` (sync)\n" \
        "    or ``await`` :meth:`execute_async` to send.\n" \
        '    """\n' \
        "\n" \
        "    def __init__(self):\n" \
        "        self._ops = []\n" \
        "\n" \
        "{% for method in methods %}" \
        "    def {{ method.name }}(\n" \
        "        self,\n" \
        "{% for field in method.fields %}" \
        "        {{ field.name }}: {{ field.field_type }} = {{ field.default }}{% if not loop.last %},{% endif %}\n" \
        "{% endfor %}" \
        "    ) -> 'Batch':\n" \
        "        self._ops.append({{ pb2 }}.SetPropertyOp(\n" \
        "            {{ method.oneof_field }}={{ pb2 }}.{{ method.request_type }}(\n" \
        "{% for field in method.fields %}" \
        "                {{ field.name }}={{ field.name }}{% if not loop.last %},{% endif %}\n" \
        "{% endfor %}" \
        "            )\n" \
        "        ))\n" \
        "        return self\n" \
        "\n" \
        "{% endfor %}" \
        "    async def _execute(self) -> {{ pb2 }}.SetPropertiesResponse:\n" \
        "        stub = await tempo_context().get_stub({{ pb2_grpc }}.{{ service_object }}Stub)\n" \
        "        request = {{ pb2 }}.SetPropertiesRequest(ops=self._ops)\n" \
        "        return await stub.SetProperties(request)\n" \
        "\n" \
        "    def execute(self) -> {{ pb2 }}.SetPropertiesResponse:\n" \
        "        return run_async(self._execute())\n" \
        "\n" \
        "    async def execute_async(self) -> {{ pb2 }}.SetPropertiesResponse:\n" \
        "        return await self._execute()\n" \
        "\n\n" \
        "def batch() -> Batch:\n" \
        '    """Create a new property-set batch builder."""\n' \
        "    return Batch()\n" \
        "\n\n"

    j2_environment = jinja2.Environment()
    for service_name, tempo_service_descriptor in all_services.items():
        tempo_module_name = tempo_service_descriptor.module_name.split(".")[0]
        with open(os.path.join(root_dir, f"{pascal_to_snake(tempo_module_name)}.py"), 'a') as f:
            for rpc_descriptor in tempo_service_descriptor.rpcs:
                tempo_request_descriptor = all_messages[rpc_descriptor.request_type]
                tempo_response_descriptor = all_messages[rpc_descriptor.response_type]
                templates = []
                if rpc_descriptor.client_streaming:
                    raise Exception("Client streaming RPCs are not yet supported")
                if rpc_descriptor.server_streaming:
                    templates.append(j2_environment.from_string(streaming_rpc_template))
                else:
                    templates.append(j2_environment.from_string(simple_rpc_template))
                imports = set()
                imports.add("{}_grpc".format(tempo_service_descriptor.module_name))
                imports.add(tempo_request_descriptor.module_name)
                imports.add(tempo_response_descriptor.module_name)
                for field in tempo_request_descriptor.fields:
                    if field.module_name:
                        imports.add(field.module_name)
                for template in templates:
                    f.write(template.render(
                        name=pascal_to_snake(rpc_descriptor.name),
                        rpc=rpc_descriptor,
                        service=tempo_service_descriptor,
                        request=tempo_request_descriptor,
                        response=tempo_response_descriptor,
                        imports=imports
                    ))

    # Emit a Batch builder class for any message in the proto graph that has the
    # canonical name "SetPropertyOp" and exposes its variants via a oneof named "op".
    # Each variant must be a TYPE_MESSAGE whose request type is also in all_messages.
    for proto_full_name, set_property_op_desc in list(all_messages.items()):
        if set_property_op_desc.object_name != "SetPropertyOp":
            continue
        op_variants = set_property_op_desc.oneofs.get("op")
        if not op_variants:
            continue
        # Find the service in the same proto module that exposes SetProperties.
        proto_package = proto_full_name.rsplit(".", 1)[0]
        owning_service = None
        for service in all_services.values():
            if service.module_name.split(".")[0] != set_property_op_desc.module_name.split(".")[0]:
                continue
            if any(rpc.name == "SetProperties" for rpc in service.rpcs):
                owning_service = service
                break
        if owning_service is None:
            continue

        methods = []
        for entry in op_variants:
            request_desc = all_messages.get(entry["message_proto_full_name"])
            if request_desc is None:
                continue
            # bool_op -> set_bool_property; int_array_op -> set_int_array_property
            method_name = "set_{}_property".format(
                entry["name"][:-3] if entry["name"].endswith("_op") else entry["name"]
            )
            methods.append({
                "name": method_name,
                "oneof_field": entry["name"],
                "request_type": request_desc.object_name,
                "fields": request_desc.fields,
            })

        pb2_module = set_property_op_desc.module_name        # e.g. TempoWorld.WorldControl_pb2
        pb2_grpc_module = owning_service.module_name + "_grpc"
        imports = sorted({pb2_module, pb2_grpc_module})

        tempo_module_name = set_property_op_desc.module_name.split(".")[0]
        output_file = os.path.join(root_dir, f"{pascal_to_snake(tempo_module_name)}.py")
        with open(output_file, 'a') as f:
            f.write(j2_environment.from_string(batch_template).render(
                methods=methods,
                pb2=pb2_module,
                pb2_grpc=pb2_grpc_module,
                service_object=owning_service.object_name,
                imports=imports,
            ))


def collect_input_files(project_root: Path, script_path: Path) -> List[Path]:
    """Collect all files that affect API generation."""
    files = [script_path]  # gen_api.py itself
    files.extend(find_files_filtered(project_root, {'.proto', '.Build.cs'}))
    return files


def collect_output_files(root_dir: Path) -> List[Path]:
    """Collect all generated API wrapper files."""
    # Generated files are snake_case .py files in root_dir, excluding known non-generated files
    excluded = {".gitignore", "_tempo_context.py", "TempoImageUtils.py", "TempoLidarUtils.py", "__init__.py"}
    files = []
    for f in root_dir.iterdir():
        if f.is_file() and f.suffix == ".py" and f.name not in excluded and "_pb2" not in f.name:
            files.append(f)
    return files


if __name__ == "__main__":
    if sys.version_info[0] < 3 or sys.version_info[1] < 9:
        raise Exception("This script requires Python 3.9 or greater (found {}.{}.{})"
                        .format(sys.version_info[0], sys.version_info[1], sys.version_info[2]))

    if len(sys.argv) < 3:
        print("Usage: gen_api.py <project_root> <plugin_root>", file=sys.stderr)
        sys.exit(1)

    project_root = Path(sys.argv[1])
    plugin_root = Path(sys.argv[2])
    root_dir = Path(os.path.dirname(os.path.realpath(__file__))) / "API" / "tempo"
    # Insert at the front so local generated pb2 files shadow any stale copy installed in the
    # venv's site-packages. Also matches the top-level import names that protoc emits inside each
    # pb2 file (e.g. `from TempoLidar import Lidar_pb2`), so every pb2 module is loaded exactly
    # once and only registers its descriptor once.
    sys.path.insert(0, str(root_dir))

    # Check cache
    cache = PrebuildCache(plugin_root / ".tempo_prebuild_cache.json")
    input_files = collect_input_files(project_root, Path(__file__))
    output_files = collect_output_files(root_dir)

    if cache.is_valid("gen_api", input_files, output_files,
                      input_base=project_root, output_base=root_dir):
        print("[Tempo Prebuild]  Skipping Python API generation (no changes detected)", flush=True)
        sys.exit(0)

    print("[Tempo Prebuild] Generating Python API", flush=True)
    generate_tempo_api(str(root_dir))

    # Update cache after successful generation
    output_files = collect_output_files(root_dir)
    cache.update("gen_api", input_files, output_files,
                 input_base=project_root, output_base=root_dir)
