// Copyright Tempo Simulation, LLC. All Rights Reserved
//
// Auto-generated by gen_rust_api.py. Do not edit.

//! High-level API wrappers for Greeter.



/// Greet
pub async fn greet_async(
    message: String,
) -> Result<crate::proto::greeter::GreeterResponse, crate::TempoError> {
    let mut ctx = crate::context::CONTEXT.write().await;
    let channel = ctx.channel().await?;
    let mut client = crate::proto::greeter::greeter_service_client::GreeterServiceClient::new(channel);

    let request = crate::proto::greeter::GreeterRequest {
        message,
    };

    let response = client.greet(request).await?;
    Ok(response.into_inner())
}

/// Synchronous version of greet
pub fn greet(
    message: String,
) -> Result<crate::proto::greeter::GreeterResponse, crate::TempoError> {
    let rt = tokio::runtime::Runtime::new()?;
    rt.block_on(greet_async(
        message,
    ))
}
