// Copyright Tempo Simulation, LLC. All Rights Reserved
//
// Auto-generated by gen_rust_api.py. Do not edit.

//! High-level API wrappers for TempoMovement.



/// GetCommandablePawns
pub async fn get_commandable_pawns_async(
) -> Result<crate::proto::tempo_movement::CommandablePawnsResponse, crate::TempoError> {
    let channel = crate::context::connected_channel().await?;
    let mut client = crate::proto::tempo_movement::movement_control_service_client::MovementControlServiceClient::new(channel)
        .max_decoding_message_size(crate::context::MAX_MESSAGE_SIZE)
        .max_encoding_message_size(crate::context::MAX_MESSAGE_SIZE);

    let request = crate::proto::tempo_core::Empty {
    };

    let response = client.get_commandable_pawns(request).await?;
    Ok(response.into_inner())
}

/// Synchronous version of get_commandable_pawns
pub fn get_commandable_pawns(
) -> Result<crate::proto::tempo_movement::CommandablePawnsResponse, crate::TempoError> {
    crate::context::RUNTIME.block_on(get_commandable_pawns_async(
    ))
}

/// CommandVehicle
pub async fn command_vehicle_async(
    vehicle: String,
    acceleration: f32,
    steering: f32,
) -> Result<crate::proto::tempo_core::Empty, crate::TempoError> {
    let channel = crate::context::connected_channel().await?;
    let mut client = crate::proto::tempo_movement::movement_control_service_client::MovementControlServiceClient::new(channel)
        .max_decoding_message_size(crate::context::MAX_MESSAGE_SIZE)
        .max_encoding_message_size(crate::context::MAX_MESSAGE_SIZE);

    let request = crate::proto::tempo_movement::NormalizedDrivingCommand {
        vehicle,
        acceleration,
        steering,
    };

    let response = client.command_vehicle(request).await?;
    Ok(response.into_inner())
}

/// Synchronous version of command_vehicle
pub fn command_vehicle(
    vehicle: String,
    acceleration: f32,
    steering: f32,
) -> Result<crate::proto::tempo_core::Empty, crate::TempoError> {
    crate::context::RUNTIME.block_on(command_vehicle_async(
        vehicle,
        acceleration,
        steering,
    ))
}

/// CommandVelocity
pub async fn command_velocity_async(
    pawn: String,
    twist: crate::proto::tempo_core::Twist,
) -> Result<crate::proto::tempo_core::Empty, crate::TempoError> {
    let channel = crate::context::connected_channel().await?;
    let mut client = crate::proto::tempo_movement::movement_control_service_client::MovementControlServiceClient::new(channel)
        .max_decoding_message_size(crate::context::MAX_MESSAGE_SIZE)
        .max_encoding_message_size(crate::context::MAX_MESSAGE_SIZE);

    let request = crate::proto::tempo_movement::VelocityCommand {
        pawn,
        twist: Some(twist),
    };

    let response = client.command_velocity(request).await?;
    Ok(response.into_inner())
}

/// Synchronous version of command_velocity
pub fn command_velocity(
    pawn: String,
    twist: crate::proto::tempo_core::Twist,
) -> Result<crate::proto::tempo_core::Empty, crate::TempoError> {
    crate::context::RUNTIME.block_on(command_velocity_async(
        pawn,
        twist,
    ))
}

/// CommandAcceleration
pub async fn command_acceleration_async(
    pawn: String,
    accel: crate::proto::tempo_core::Accel,
) -> Result<crate::proto::tempo_core::Empty, crate::TempoError> {
    let channel = crate::context::connected_channel().await?;
    let mut client = crate::proto::tempo_movement::movement_control_service_client::MovementControlServiceClient::new(channel)
        .max_decoding_message_size(crate::context::MAX_MESSAGE_SIZE)
        .max_encoding_message_size(crate::context::MAX_MESSAGE_SIZE);

    let request = crate::proto::tempo_movement::AccelerationCommand {
        pawn,
        accel: Some(accel),
    };

    let response = client.command_acceleration(request).await?;
    Ok(response.into_inner())
}

/// Synchronous version of command_acceleration
pub fn command_acceleration(
    pawn: String,
    accel: crate::proto::tempo_core::Accel,
) -> Result<crate::proto::tempo_core::Empty, crate::TempoError> {
    crate::context::RUNTIME.block_on(command_acceleration_async(
        pawn,
        accel,
    ))
}

/// GetNavigablePawns
pub async fn get_navigable_pawns_async(
) -> Result<crate::proto::tempo_movement::NavigablePawnsResponse, crate::TempoError> {
    let channel = crate::context::connected_channel().await?;
    let mut client = crate::proto::tempo_movement::movement_control_service_client::MovementControlServiceClient::new(channel)
        .max_decoding_message_size(crate::context::MAX_MESSAGE_SIZE)
        .max_encoding_message_size(crate::context::MAX_MESSAGE_SIZE);

    let request = crate::proto::tempo_core::Empty {
    };

    let response = client.get_navigable_pawns(request).await?;
    Ok(response.into_inner())
}

/// Synchronous version of get_navigable_pawns
pub fn get_navigable_pawns(
) -> Result<crate::proto::tempo_movement::NavigablePawnsResponse, crate::TempoError> {
    crate::context::RUNTIME.block_on(get_navigable_pawns_async(
    ))
}

/// PawnMoveToLocation
pub async fn pawn_move_to_location_async(
    pawn: String,
    location: crate::proto::tempo_core::Vector,
    relative: bool,
) -> Result<crate::proto::tempo_movement::PawnMoveToLocationResponse, crate::TempoError> {
    let channel = crate::context::connected_channel().await?;
    let mut client = crate::proto::tempo_movement::movement_control_service_client::MovementControlServiceClient::new(channel)
        .max_decoding_message_size(crate::context::MAX_MESSAGE_SIZE)
        .max_encoding_message_size(crate::context::MAX_MESSAGE_SIZE);

    let request = crate::proto::tempo_movement::PawnMoveToLocationRequest {
        pawn,
        location: Some(location),
        relative,
    };

    let response = client.pawn_move_to_location(request).await?;
    Ok(response.into_inner())
}

/// Synchronous version of pawn_move_to_location
pub fn pawn_move_to_location(
    pawn: String,
    location: crate::proto::tempo_core::Vector,
    relative: bool,
) -> Result<crate::proto::tempo_movement::PawnMoveToLocationResponse, crate::TempoError> {
    crate::context::RUNTIME.block_on(pawn_move_to_location_async(
        pawn,
        location,
        relative,
    ))
}

/// RebuildNavigation
pub async fn rebuild_navigation_async(
) -> Result<crate::proto::tempo_core::Empty, crate::TempoError> {
    let channel = crate::context::connected_channel().await?;
    let mut client = crate::proto::tempo_movement::movement_control_service_client::MovementControlServiceClient::new(channel)
        .max_decoding_message_size(crate::context::MAX_MESSAGE_SIZE)
        .max_encoding_message_size(crate::context::MAX_MESSAGE_SIZE);

    let request = crate::proto::tempo_core::Empty {
    };

    let response = client.rebuild_navigation(request).await?;
    Ok(response.into_inner())
}

/// Synchronous version of rebuild_navigation
pub fn rebuild_navigation(
) -> Result<crate::proto::tempo_core::Empty, crate::TempoError> {
    crate::context::RUNTIME.block_on(rebuild_navigation_async(
    ))
}
