# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TempoAgentsEditor/TempoAgentsEditor.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from TempoScripting import Empty_pb2 as TempoScripting_dot_Empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)TempoAgentsEditor/TempoAgentsEditor.proto\x12\x11TempoAgentsEditor\x1a\x1aTempoScripting/Empty.proto\"!\n\x0ePipelineResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32x\n\x18TempoAgentsEditorService\x12\\\n RunTempoZoneGraphBuilderPipeline\x12\x15.TempoScripting.Empty\x1a!.TempoAgentsEditor.PipelineResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TempoAgentsEditor.TempoAgentsEditor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PIPELINERESULT']._serialized_start=92
  _globals['_PIPELINERESULT']._serialized_end=125
  _globals['_TEMPOAGENTSEDITORSERVICE']._serialized_start=127
  _globals['_TEMPOAGENTSEDITORSERVICE']._serialized_end=247
# @@protoc_insertion_point(module_scope)
